Cargo.lock, Cargo.toml, src/checker.rs, src/main.rs, src/options.rs
This PR addresses #4.
Note that I'm somewhat new to Rust so I would really appreciate feedback.
One part of this PR that felt a little off to me was having to add lifetime annotation to `Checker`.
Let me know if there is a better way.
=> Show the progress interactively with progress bar and in-flight requests (--progress)

Cargo.lock, Cargo.toml, src/checker.rs, src/main.rs, src/options.rs
[Issue #18](https://github.com/hello-rust/lychee/issues/18)
* Add headers crate to type headers and create auth header
* Add cmd param basic-auth to set property to the checker
* Add simple test to test if with auth headres is no broken
Signed-off-by: FabianBG <f4b4g3@gmail.com>
=> Add support for basic auth #18

.editorconfig, README.md, TROUBLESHOOTING.md
Having noticed a typo I have decided to fix inconsistent whitespace in the troubleshooting document as well.
While at it, I added `.editorconfig` file (see [EditorConfig](https://editorconfig.org/)) which should make it easier to maintain consistent indentation and white space handling throughout the project.
=> Update troubleshooting guide, add .editorconfig

.dockerignore, .github/workflows/docker.yml, Dockerfile, Makefile
Adds an initial Docker image to the repo.
*TODO*
=> Add Docker image #40

README.md
I was able to use lychee successfully with my links repo: https://github.com/pawroman/links
In the process, I decided to add instructions for GitHub token, and add my repo as first user :wink: 
Here's how to make it work with GitHub actions: https://github.com/pawroman/links/blob/master/.github/workflows/main.yml#L12-L25 -- It's not ideal, but it's a start. It will be useful for creating a dedicated GitHub action.
Straight off the bat, I see an issue with `--progress` flag in actions. Will investigate in spare time.
=> Update GitHub token info, add my repo as user

.github/workflows/links.yml
=> Use lychee for checking links in the lychee repo

README.md, TROUBLESHOOTING.md
It needs some more publicity. :smile: 
Also mention GitHub token in TROUBLESHOOTING.md
=> Mention GitHub Action in README.md

Cargo.lock, Cargo.toml, README.md, src/bin/lychee/main.rs, src/bin/lychee/options.rs, src/bin/lychee/stats.rs, src/client.rs, src/client_pool.rs, src/excludes.rs, src/extract.rs, src/lib.rs, src/types.rs, tests/usage.rs
Adds a new function `lychee::check()`, which removes
a lot of boilerplate for simple cases. Adjusted the code,
tests, and documentation.
The downside is that `check` now returns a Result, so
we have to use `?` to get to the response. That's because
we have to account for the case where the given string is
not a valid URI.
=> Improve lychee ergonomics

tests/usage.rs
Fixes the test failure introduced by 2d724c2d38d22741f2da56f3c6bf6e5c7f95b96c
=> Fix usage test after README.md code fence change

Cargo.toml
The solution is simple, add `[patch]` section.
=> fixed issues in Cargo.toml that blocks publishing

Cargo.lock, Cargo.toml
One less dependency hack :smile:
=> Bump check-if-email-exists to latest

lychee-lib/src/quirks/mod.rs
=> Use thumbnail endpoint for YouTube videos

lychee-lib/src/client.rs, lychee-lib/src/quirks/mod.rs
See also https://github.com/lycheeverse/lychee/issues/37
=> Fix crates.io 404 with quirk

.github/workflows/rust.yml
Coming from https://github.com/lycheeverse/lychee/pull/309#issuecomment-912984490. This makes lychee publish idempotent.
=> Use cargo-publish-all for release.

README.md, lychee-bin/src/main.rs, lychee-bin/src/options.rs, lychee-lib/src/client.rs
I'm not very fixed on the flag's name, it's the best I could come up with after a few minutes of thinking about it. Suggestions for different names welcome!
=> Add no check (dump links only) flag

lychee-lib/src/client.rs
In https://github.com/lycheeverse/lychee/pull/137 we excluded mail addresses from getting checked when setting `--exclude-all-private`. See https://github.com/lycheeverse/lychee/pull/137#discussion_r703851118
This PR fixes it.
=> Don't exlude mail on `exclude-all-private`

lychee-bin/tests/cli.rs, lychee-lib/src/extract.rs, lychee-lib/src/helpers/path.rs
@ran-huang, @MichaIng this should fix the issues we see in #320.
=> Silently ignore absolute paths without base (fixes #320)

.github/workflows/docker.yml
Discussion: https://github.com/lycheeverse/lychee/issues/321#issuecomment-919161530
@fauust is that how you imagined it or is there a better way?
=> Don't try to publish Docker image on fork

.github/workflows/links.yml
https://github.com/lycheeverse/lychee/pull/332#issuecomment-922761879
=> Skip creating issues on forks

lychee-bin/src/main.rs
This way the normal link output can be fed into
another tool without data mangling.
=> Only print source in verbose mode

.github/workflows/docker-new.yml, .github/workflows/rust.yml, Dockerfile-CI.Dockerfile
=> [WIP] publish arm64 docker image

Cargo.lock, lychee-lib/Cargo.toml, lychee-lib/src/types/uri.rs
Fixes https://github.com/lycheeverse/lychee/issues/431
=> Exclude known false-positives from Github API check

README.md, lychee-bin/src/options.rs, lychee-bin/tests/cli.rs, lychee-lib/src/client.rs, lychee-lib/src/lib.rs
Using the same default values for the library and the
binary now. Tweaked the values a bit.
=> Make retries configurable; align constants

lychee-lib/src/types/error.rs
Using pattern matching to make the hubcaps and reqwest error messages a little shorter and (subjectively) more readable.
=> Simplify error messages

lychee-lib/src/client.rs, lychee-lib/src/types/error.rs, lychee-lib/src/types/mail.rs, lychee-lib/src/types/mod.rs, lychee-lib/src/types/uri.rs
=> Add more information about mail errors

.github/workflows/docker.yml
See https://github.com/docker/login-action/issues/65
=> Disable Docker login for dependabot

lychee-lib/src/client.rs
With the refactoring the URL checking as a workaround for the upstream
reqwest panic on invalid URLs, we introduced a regression, which caused
unsupported URL schemes to show up as errors in the lychee output.
This commit changes the behavior such that invalid schemes get ignored
again by making a differentiation between truly invalid URIs which would make
reqwest panic, and ones which are valid but just not handled by reqwest.
The check was moved to `check_website` such that the invalid URIs would
not be checked three times in a loop before erroring out.
=> Regression: Ignore invalid URLs (fixes #562)

lychee-bin/src/commands/check.rs
as suggested here: https://github.com/lycheeverse/lychee/pull/570#discussion_r835931903
=> Minor coding enhancement

lychee-lib/src/extract/html5gum.rs
See https://github.com/lycheeverse/lychee/pull/572#issuecomment-1087954376 by @untitaker
=> Reset nofollow in html5gum start tag

fixtures/configs/smoketest.toml, lychee-bin/src/options.rs, lychee-bin/tests/cli.rs, lychee.example.toml
Fixes #630 
Easy test `./lychee -c lychee.example.toml -- README.md`
=> Improve configuration example

Cargo.lock, fixtures/configs/smoketest.toml, lychee-bin/Cargo.toml, lychee-bin/src/options.rs, lychee-lib/src/types/base.rs, lychee.example.toml
As discussed in https://github.com/lycheeverse/lychee/issues/630.
@vpereira01 fyi.
=> Fix parsing errors with config options

docs/TROUBLESHOOTING.md
See details: https://github.com/lycheeverse/lychee-action/issues/152
=> Update Troubleshooting Guide

Cargo.lock, lychee-bin/src/formatters/response/raw.rs, lychee-bin/src/formatters/stats/detailed.rs, lychee-bin/src/formatters/stats/markdown.rs, lychee-lib/src/extract/markdown.rs, lychee-lib/src/types/error.rs, lychee-lib/src/types/response.rs, lychee-lib/src/types/status.rs, lychee-lib/src/types/uri/raw.rs
This is a little more verbose than I want, but the output provides more detailed information about why a request failed.
It's an attempt to fix the regression mentioned at https://github.com/lycheeverse/lychee-action/issues/148
```markdown
> cargo run --  --format=markdown https://httpstat.us/
| Status        | Count |
|---------------|-------|
| 🔍 Total      | 85    |
| ✅ Successful | 29    |
| ⏳ Timeouts   | 3     |
| 🔀 Redirected | 4     |
| 👻 Excluded   | 0     |
| ❓ Unknown    | 1     |
| 🚫 Errors     | 48    |
* [413] [https://httpstat.us/413](https://httpstat.us/413) | Failed: Network error: Payload Too Large
* [501] [https://httpstat.us/501](https://httpstat.us/501) | Failed: Network error: Not Implemented
* [403] [https://httpstat.us/403](https://httpstat.us/403) | Failed: …
```
=> Markdown-status

lychee-lib/src/quirks/mod.rs
Use an alternative Twitter frontend, which works more reliably than
using Twitter directly.
Fixes #448
=> Check Twitter URLs using nitter.net

.github/workflows/ci.yml, lychee-bin/Cargo.toml
`cargo-publish-all` is not well maintained
=> Move back to cargo publish

README.md
=> Add note about lychee.toml and exclude_path to README.md

Makefile, lychee-bin/src/commands/check.rs, lychee-bin/src/main.rs, lychee-bin/src/parse.rs, lychee-bin/tests/cli.rs, lychee-lib/src/types/cache.rs, lychee-lib/src/types/error.rs, lychee-lib/src/types/status.rs
=> Allow overriding accepted status codes for cached URIs

lychee-bin/src/options.rs
Forgot the serde defaults which lead to problems on some terminals
=> Fix verbosity serialization

lychee-lib/src/types/file.rs
=> Add more markdown extensions

.github/workflows/auto-merge.yml
With the latest changes in https://github.com/lycheeverse/lychee/pull/893 I think I broke automerge. Reverting some of the changes to fix that.
=> Fix automerge config

lychee-lib/src/quirks/mod.rs
Previously those were not correctly rewritten to thumbnail URLs.
This should be fixed now by splitting up the logic
for normal YouTube links and shortlinks.
Fixes #906
=> Properly handle youtu.be shortlinks

.github/workflows/ci.yml
Test if it speeds up compile times
=> Experiment with Github actions cache

README.md
https://archlinux.org/packages/community/x86_64/lychee/
=> Update name of Arch package

lychee-lib/src/extract/html5ever.rs, lychee-lib/src/extract/html5gum.rs, lychee-lib/src/extract/mod.rs
=> Avoid false positives when checking email addresses in HTML input

.github/workflows/nightly.yml
- fix https://github.com/lycheeverse/lychee/pull/1224#issuecomment-1682339534
=> ignore the error when deleting nightly tags

README.md, fixtures/configs/smoketest.toml, lychee-bin/src/options.rs, lychee.example.toml
Fixes https://github.com/lycheeverse/lycheeverse.github.io/issues/7
=> Mention supported schemes

fixtures/TEST_EXAMPLE_DOMAINS.md, fixtures/TEST_EXAMPLE_DOMAINS_FALSE_POSITIVES.md, lychee-bin/tests/example_domains.rs, lychee-lib/src/filter/mod.rs
Fixes https://github.com/lycheeverse/lychee/issues/1283
=> Exclude example TLDs from RFC 2606

README.md
`lychee` is now available for Alpine Linux 🥳
<https://pkgs.alpinelinux.org/packages?name=lychee>
=> docs: add instructions for installing on Alpine Linux

lychee-bin/src/formatters/stats/compact.rs, lychee-lib/src/chain/mod.rs, lychee-lib/src/remap.rs
Addresses https://github.com/lycheeverse/lychee/issues/1477
=> Extend compact format

lychee.example.toml
=> Fix example usage of headers in configuration file

.github/workflows/links.yml
New run: https://github.com/thomas-zahner/lychee/actions/runs/11484715391
Old run: https://github.com/thomas-zahner/lychee/actions/runs/11466179824
=> Update link check action

.github/workflows/docker.yml, Dockerfile-CI.Dockerfile, Dockerfile-CI.alpine.Dockerfile
Resolves #1582
@mre any thoughts on how to test this?
=> Fix nightly docker image

README.md
added a link to the shield and to the license
=> chore: added a link to the shield and to the license

.github/workflows/docker.yml
Attempt to fix the issues described in https://github.com/lycheeverse/lychee/issues/1628#issuecomment-2651206799.
I'm still not 100% sure if this works.
=> Update Docker Workflow To Support Version Tags

README.md
FreeBSD 从入门到跑路 A book about FreeBSD.
=> Add FreeBSD-Ask to users

Cargo.lock, lychee-bin/src/archive/wayback/mod.rs, lychee-bin/src/commands/check.rs, lychee-bin/src/formatters/color.rs, lychee-bin/src/formatters/response/color.rs, lychee-bin/src/formatters/stats/compact.rs, lychee-bin/src/stats.rs, lychee-lib/Cargo.toml, lychee-lib/src/client.rs, lychee-lib/src/extract/markdown.rs, lychee-lib/src/filter/mod.rs, lychee-lib/src/quirks/mod.rs, lychee-lib/src/types/accept/range.rs, lychee-lib/src/types/input.rs, lychee-lib/src/types/status.rs, lychee-lib/src/types/uri/github.rs, lychee-lib/src/types/uri/valid.rs, lychee-lib/src/utils/fragment_checker.rs, lychee-lib/src/utils/path.rs, lychee-lib/src/utils/url.rs
resolves all clippy issues
sry for the messed up commit history
=> make clippy happy

.github/workflows/ci.yml, Makefile
As discussed in https://github.com/lycheeverse/lychee/pull/1676#issuecomment-2866757002
I added to the lint job to balance the time spent on CI.
=> chore: verify the MSRV in CI lint

Makefile, lychee-bin/tests/example_domains.rs
=> Fix `test_exclude_example_domains`

lychee-lib/src/extract/html/html5ever.rs, lychee-lib/src/extract/html/html5gum.rs
- fix https://github.com/lycheeverse/lychee/issues/1682
=> feat: respect the `disabled` property for stylesheet links

fixtures/ignore/ignored-file.md
Could be that Archlinux is somehow limiting requests coming from GitHub
=> Replace URL to fix GitHub CI

.github/workflows/update-toc.yml
Fixes workflow step by adding permission. For example see: https://github.com/lycheeverse/lychee/actions/runs/17156732718/job/48675283116
=> Add content write permissions

README.md
Uses the conda-forge builds, available on most platforms (Linux, Windows, macOS).
=> add conda install to readme

lychee-bin/src/formatters/response/plain.rs, lychee-bin/src/formatters/response/task.rs, lychee-bin/src/formatters/stats/detailed.rs, lychee-bin/src/formatters/stats/markdown.rs, lychee-bin/src/formatters/suggestion.rs, lychee-bin/src/main.rs, lychee-bin/src/stats.rs, lychee-bin/tests/cli.rs, lychee-lib/src/types/redirect_history.rs, lychee-lib/src/types/status.rs
Closes #1433
Here is the follow-up PR of the redirect reporting. I previously forgot about it.
=> Additional redirect reporting
