lycheeverse/lychee

- .github/workflows/rust.yml
I don't know why but having most up-to-date Rust toolchain addressed #6.
This PR makes it so that we use `actions-rs/toolchain@v1` which always installs the latest stable versions.
The code is mostly copied from https://github.com/marketplace/actions/rust-cargo.
> Use action-rs Actions instead

- Cargo.lock
- Cargo.toml
- fixtures/TEST_ALL_PRIVATE.md
- src/checker.rs
- src/extract.rs
- src/main.rs
- src/options.rs
- tests/cli.rs
Currently, the excludes are based purely on IP address ranges and only work for websites (no support for mail addresses). The IPv6 support is implemented, to a degree possible with Rust standard library as of 1.47.0. See commit messages and code comments for more details.
Note: while IP address exclude works, it's possible that some URLs will resolve to link-local, private or loopback addresses. While this is not very likely, it's a possibility. To address this, we'd have to DNS-resolve all URIs and then run them through IP exclude rules. I have skipped this part because of extra effort involved.
Closes #5.
> Add exclude private URLs feature

- .github/workflows/rust.yml
- src/checker.rs
- src/main.rs
Following up on changes in #9, I have noticed that the new action definition only performs a `build`, without running the tests.
This PR introduces the following changes:
- The tests are ran as part of the `test` actions workflow, no longer merely building the code.
- The new `lints` actions workflow adds checks for:
- `cargo fmt` (checks if all code is formatted using `rustfmt`)
- `cargo clippy` (checks if there's any warnings produced by [clippy](https://github.com/rust-lang/rust-clippy)). In the process of adding this, I have addressed all the clippy warnings. There's one warning which I silenced, see: https://github.com/hello-rust/lychee/pull/10/files#diff-80d406c60c48b139f4acbeb1b43605d26970cf1de2e39e423ebcf701051e63faR86 -- That I think should be tackled in a separate PR.
> Actions improvements: add rustfmt and clippy checks, run tests

- src/checker.rs
Fixes #1 
Implement retry/exponential backoff in check_real as follow:
https://users.rust-lang.org/t/how-to-do-exponential-backoff-with-futures/45285
it’s the simplest way to make it possible to be backoffed.
> Support exponential backoff in check_real #1

- Cargo.lock
- Cargo.toml
- src/checker.rs
I have noticed that the `test_timeout` was ignored. I managed to get it working.
Even though it might not be testing what was originally intended, it's still a good test to have.
This also bumps the `wiremock` library used to mock the HTTP servers in tests to 0.3, latest stable release.
Should be merged after #10 so that the test is ran in GitHub actions.
> Un-ignore test_timeout, upgrade wiremock to 0.3

- Cargo.lock
- Cargo.toml
- fixtures/TEST.html
- fixtures/TEST_ALL_PRIVATE.md
- src/collector.rs
- src/extract.rs
- src/main.rs
- src/options.rs
Sorry for the delay. :smile: :laughing: Fixes #3
> feat: Relative Url

- README.md
- lychee.example.toml
- src/checker.rs
- src/main.rs
- src/options.rs
In case one or more `include` arguments are specified, only check the URLs that match the patterns.
In case `exclude` arguments are also specified, make an exception from the excluded URLs if they also match the `include` patterns.
> Add support for `include` patterns (fixes #19)

- README.md
- fixtures/TEST_404.md
- fixtures/TEST_GITHUB.md
- fixtures/TEST_GITHUB_404.md
- fixtures/TEST_GITHUB_TOKEN.md
- src/checker.rs
- src/main.rs
- src/options.rs
- tests/cli.rs
This also makes the token possible to pass in from CLI args.
I got bitten by this a few times, and decided that issuing a warning instead of failing would be a better choice in terms of user experience.
Happy to tweak the behavior to if you think the new default is not an improvement over the old one.
> Make GITHUB_TOKEN optional

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/options.rs
- src/types.rs
Just a couple of cleanups I made while browsing the source-code. 
@pawroman I'm not sure if it's worth your time to do a code-review here but I'll keep that open for a while just in case. 😉 
Perhaps the biggest change is that we're now using `lychee/0.3.1` as the user agent name. It can still be overwritten of course.
> Properly announce lychee user agent

- .github/workflows/rust.yml
See #59 
Pipeline code taken from https://github.com/EmbarkStudios/tryhard/blob/main/.github/workflows/rust-ci.yml
> Publish releases on crates.io

- README.md
Not sure if that's an omission or of I missed something, but I believe that checking local `.html` files works in linkchecker.
> linkchecker supports HTML files

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
This creates lychee binaries for every release. 
See #59 for more info.
Created a fake release [here](https://github.com/mre-early-access/lychee/releases/tag/v0.6.2) to show how the output looks like.
Some notes:
* mips builds are not supported by `ring` at the moment, which is a sub-dependency. reqwests has support for rustls through a [feature flag](https://github.com/seanmonstar/reqwest/blob/master/Cargo.toml#L37), but I doubt that it supports mips either.
* With around 26 minutes, the windows builds take the longest time. (2-3x as long as macOS and Linux.) I don't know why this is; the compile step is just slower. ¯\_(ツ)_/¯
* Introducing a feature flag for using [vendored openssl](https://docs.rs/openssl/0.10.31/openssl/#vendored) as it prevents headaches with the OpenSSL shared …
> Build binaries for Linux, Windows, and macOS for every release

- .dockerignore
- Dockerfile
Move `lychee` binary to `/usr/local/bin` to make it callable
without a full path.
This makes it easier to use from the lychee Github action
in the future.
Also the user setup is making things unnecessary complicated
and could be prohibited in some environments so this commit
is removing it and uses the defaults.
> Cleanup Docker image

- Cargo.lock
- Cargo.toml
- fixtures/TEST.md
- src/bin/lychee/main.rs
- src/bin/lychee/options.rs
- src/bin/lychee/stats.rs
- src/uri.rs
- tests/cli.rs
This PR adds two new flags:
`--output` for defining an output file for the status report.
`--format` for setting the output format (only `string` and `json` supported for now)
I honestly don't know if it makes sense to include formats other than string or JSON.
For example, MD and HTML are not really machine-readable. YAML is not
a great standard format for this use-case. Open for discussions, though.
These features come in handy for the new [lychee Github action](https://github.com/lycheeverse/lychee-action/).
> Add output file support (fixes #53)

- .github/workflows/rust.yml
- src/extract.rs
The test code should also be linted.
Also fixes the code in tests that was failing the lints.
> Run clippy for all targets, including tests

- fixtures/TEST_HTML5.html
- src/extract.rs
Addresses #83 (does not solve all the uncovered issues, but fixes early parsing stop).
The XML parser we use requires all tags to be closed by default,
and if they aren't (like HTML5 `<link>` elements), it simply gives up
on further parsing.  This change makes it ignore such issues.
Also uncover a bug with the current parser (it simply won't parse
elements like `<script defer src="..."></script>`) -- e.g. elements
with no attribute values.
The XML parser is an XML parser and will have to be replaced with
HTML aware parser in the future.
> Fix HTML parsing for non-closed elements like <link>

- README.md
- tests/readme.rs
This makes it impossible to have diverged `--help` and `README.md`.
Will come in useful when adding new flags.
> Test that cli parameters / usage are in sync in README.md

- src/bin/lychee/main.rs
See comments in code for more details.
This *might* be related to #131, but I'm not sure. Definitely worth a shot though.
> Ensure destructors are ran before std::process::exit

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/lychee/main.rs
- src/bin/lychee/options.rs
- src/bin/lychee/stats.rs
- src/client.rs
- src/client_pool.rs
- src/collector.rs
- src/extract.rs
- src/lib.rs
- src/test_utils.rs
- src/types.rs
- src/uri.rs
- tests/cli.rs
If an error occurs during link checking,
it is important to know where the error occurred.
Therefore the request and response objects now contain a the input
source as a field. This makes error tracking easier.
>  Show input source in status output

- src/bin/lychee/main.rs
- src/bin/lychee/stats.rs
Ensure that no extra newlines are printed in the output.
See comparison below:
| Before | This MR |
|---|---|
| ![empty-file-before](https://user-images.githubusercontent.com/914977/111042499-fa2c2280-843d-11eb-874a-99e025eddc20.png) | ![empty-file-after](https://user-images.githubusercontent.com/914977/111042512-04e6b780-843e-11eb-907f-9820e16fd3a4.png) |
| ![non-verbose-before](https://user-images.githubusercontent.com/914977/111042522-1039e300-843e-11eb-9319-8762e68247bd.png) | ![non-verbose-after](https://user-images.githubusercontent.com/914977/111042531-162fc400-843e-11eb-8c76-bc61b9b62ab0.png) |
|  ![verbose-before](https://user-images.githubusercontent.com/914977/111042534-1cbe3b80-843e-11eb-9fbc-31994951b0ac.png) | ![verbose-after](https://user-images.githubusercontent.com/914977/ …
> Avoid extra newlines in output

- Cargo.lock
- Cargo.toml
- src/extract.rs
- src/uri.rs
Only consider a link an email if it fails to parse as URL.
Also use a proper email validation instead of a simple '@' check.
This uses the fast_chemail crate which parses email links according
to the HTML specification (which is much more practical than checking
for RFC 5322 formatted emails).  It's also worth noting that
fast_chemail is used internally (albeit indirectly) by the
check_if_email_exists crate.  This means that email addresses
not considered valid by fast_chemail wouldn't pass link checks
anyway.
Fixes #161.
> Fix URLs with '@' parsing as emails

- src/filter/excludes.rs
- src/filter/mod.rs
Some URIs will be excluded by default.
This can be overwritten by the user by
explicitly using `--include`.
> Define set of well-known false-positives (fixes #169)

- src/client.rs
Only check real Github URLs through the API, starting with an optional scheme and an optional www subdomain:
```
http://github.com
https://github.com
https://www.github.com
www.github.com
github.com
```
> Only allow true Github links to be checked through the API

- src/quirks/mod.rs
Non-video YouTube links (which don't have `/watch` as a path), should not be rewritten.
These can be channel links. See https://github.com/mre/idiomatic-rust/issues/22 for an example of a false positive.
> Only use oembed on YT video links (fixes #198)

- lychee.example.toml
Hey, I tried to use the example config file on my personal website and found a small bug. 
In addition, I added `exclude_mail` to the configuration file.
> Improve example configuration file

- Cargo.lock
- README.md
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/src/stats.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/filter/excludes.rs
- lychee-lib/src/filter/includes.rs
- lychee-lib/src/filter/mod.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/test_utils.rs
- lychee-lib/src/uri.rs
- Major changes in `lychee-lib::filter` module:
- Fields in `Excludes` except the `RegexSet` is now moved to `Filter`.
- `Filter` contains `Option<Excludes>` and `Option<Includes>`, which are
wrapper struct of `RegexSet` instead of `Option<RegexSet>`. As a result
the code now looks cleaner.
- Factored out some filtering logics to dedicated functions.
- It's possible to write tests for those functions in addition to tests
for the `Filter` struct.
- Added docs to `Filter::is_excluded` and reorgnized the code.
- placed `derive_builder` by `typed_builder`:
- The internal interface very ugly, as admitted by the author, but we no
longer have nested `Option`s like before.
- As a result, the `Client` building is much easier to read.
- Main benefit of `typed_builder` is, the arguments feeded to …
> More refactor

- fixtures/TEST_QUIRKS.txt
- fixtures/TEST_SCHEMES.txt
- lychee-bin/src/stats.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/status.rs
> Skip unsupported schemes 

- README.md
- fixtures/TEST_SCHEMES.md
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/filter/mod.rs
For example
```
lychee https://example.org --scheme http --scheme https
```
This will check all links on example.org, which have `http` or `https` as a scheme. 
Perhaps surprisingly, this will **still** check the contents of http://example.org:
```
lychee http://example.org --scheme https
```
It will merely skip the non-https link **on that page**:
```
> lychee http://example.org --scheme https
✔ https://www.iana.org/domains/example [200 OK]
📝 Summary
---------------------
🔍 Total............1
✅ Successful.......1
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........0
```
We can decide whether we want to exclude **input URLs** that don't specify a selected scheme, but I'd change that in a separate PR (or not at all).
My current thinking is that if the user …
> Add support for multiple schemes

- .gitignore
- README.md
- fixtures/TEST.md
- fixtures/TEST_EXCLUDE_1.txt
- fixtures/TEST_EXCLUDE_2.txt
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/src/stats.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/extract.rs
- lychee-lib/src/quirks/mod.rs
- lychee.example.toml
Implemented https://github.com/lycheeverse/lychee/issues/302.
This is my first rust code, so talk to me like a 2yo :)
> Implements --exclude-file

- .github/workflows/rust.yml
- Cargo.lock
- README.md
- examples/builder/Cargo.toml
- examples/client_pool/Cargo.toml
- examples/collect_links/Cargo.toml
- examples/simple/Cargo.toml
- lychee-bin/Cargo.toml
- lychee-lib/Cargo.toml
Fixes #305 by using [cargo-publish-all](https://crates.io/crates/cargo-publish-all) which creates a workspace first, then publishes lychee-lib into it, then publishes lychee-bin using what it just published. So now we can increment the version of lychee-lib and lychee-bin to the *next* iteration which is the code that we have now on master.
This requires a newer version of rust-type-builder with the fix for https://github.com/idanarye/rust-typed-builder/issues/57.
> Fix publish workflow

- .gitignore
- lychee-bin/src/stats.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/status.rs
> Don't panic on unknown status codes

- README.md
Additionally remove a misplaced "use" in front of the comparison table and align the code spaces within the table to enhance readability of the code (no effect on visual Markdown).
Since I just compiled it, running into 4 failures due to missing build dependencies 😉. I'd btw agree if one either wants other OSes/distros listed as well or have the dependencies listed in a more generic way, like "Rust toolchain, C compiler, libc, libssl and pkg_config" or so. So take this more as a suggestion to list build dependencies somewhere in some way, which I wanted to do in a constructive way with the copy&paste ready commands the the type or distros I use. From this, everyone should be able to derive the respective packages for the own distro, e.g. on RPM based ones it's `glibc-devel` and …
> Include build dependencies in cargo install section

- Cargo.lock
- Makefile
- README.md
- lychee-bin/Cargo.toml
- lychee-bin/src/main.rs
- lychee-lib/src/lib.rs
This enables debugging and improvement of asynchronous Rust code.
It is an optional feature that is still
experimental (but can be quite helpful)
More info: https://github.com/tokio-rs/console
> Add support for tokio-console

- .github/workflows/docker.yml
This adds a simple CI step to update the DockerHub registry with the README.md file.
For the moment, the registry overview is empty:
See #321
> Add a description on DockerHub registry

- README.md
- lychee-bin/src/options.rs
> Make inputs required (show help if not provided)

- lychee-bin/src/main.rs
When piping the output of lychee's `--dump` output to another program, we can run into issues with broken pipes as described in rust-lang/rust#46016 and https://gabebw.com/blog/2019/10/13/learning-rust-by-candlelight.
To avoid this, we use the underlying `writeln!` macro and check the returned `ErrorKind`.
**Behavior before (current master)**:
```
cargo run -- --dump README.md | grep -q 'https://hello-rust\.show'
Finished dev [unoptimized + debuginfo] target(s) in 0.60s
Running `target/debug/lychee --dump README.md`
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1193:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**Behavior after (this branch)**:
```
cargo run -- --dump README.md | grep -q …
```
> Fix broken pipe when dumping links

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- lychee-bin/Cargo.toml
- lychee-bin/src/main.rs
- lychee-bin/src/parse.rs
- lychee-bin/src/stats.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/extract.rs
- lychee-lib/src/helpers/path.rs
- lychee-lib/src/helpers/url.rs
- lychee-lib/src/types/response.rs
While profiling local file handling, I noticed that resolving paths was taking a
significant amount of time. It also caused quite a few allocations.
By caching the path and using a constant value for the current
directory, we can reduce the number of allocs by quite a lot (5%).
This is my second attempt at reducing allocs. The first one is here #345.
>  Cache `absolute_path` to decrease allocations

- README.md
- lychee-bin/src/options.rs
- lychee-lib/src/filter/mod.rs
- lychee.example.toml
as "localhost" is usually mapped via "hosts" file to a loopback IP address.
Resolves: https://github.com/lycheeverse/lychee/issues/319
> Imply "localhost" when loopback IPs are excluded

- lychee-lib/src/filter/mod.rs
https://github.com/lycheeverse/lychee-action/issues/53
@dend as discussed.
> Exclude more false positive schema domains

- lychee-lib/src/extract.rs
- lychee-lib/src/helpers/url.rs
> Remove srcset attribute from list of "link" attrs

- .github/workflows/links.yml
- Cargo.lock
- README.md
- lychee-bin/Cargo.toml
- lychee-bin/src/color.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/src/stats.rs
- lychee-bin/src/writer/compact.rs
- lychee-bin/src/writer/detailed.rs
- lychee-bin/src/writer/json.rs
- lychee-bin/src/writer/markdown.rs
- lychee-bin/src/writer/mod.rs
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/filter/mod.rs
I got a bit annoyed by the current status output.
While it sort of works, it's not too nice to look at and a little annoying to read and understand.
So I reworked it with a human user in mind. The terminal output should not be parsed by machines; that's what we have the JSON output for. That said, we might introduce a third output in the future that is closer to the old output which allows for easier grepping.
The new summary is more compact:
The error output also got a revamp and is closer to the the output of [ripgrep](https://github.com/BurntSushi/ripgrep) now:
Let me know what you think. Also a code review would be great. 😊
> Colorize and simplify status output

- Cargo.lock
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/types/error.rs
This removes some boilerplate and is arguably better
than handwriting the error handling code for
maintainability and avoid inconsitent functionality
for the error variants.
thiserror is also the de-facto standard for library
error types as of today.
> Use thiserror for error handling

- README.md
- fixtures/ignore/.lycheeignore
- fixtures/ignore/TEST.md
- fixtures/ignore/normal-exclude-file
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee.example.toml
This is similar to files like .gitignore and .dockerignore
and gets merged into exclude_files
Fixes #308
>  Add support for .lycheeignore file #308

- examples/collect_links/collect_links.rs
- lychee-bin/src/main.rs
- lychee-lib/src/collector.rs
Concurrency is defined by the channel size consuming
from the request stream in  `check`
> Max concurrency moved to check

- lychee-lib/src/types/input.rs
We recently removed the custom serialization for InputSource.
This causes the JSON formatter to fail
with "key must be a string".
Add it back and add a comment on
why this is needed.
> Fix JSON serialization

- Makefile
- lychee-lib/src/client.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/mod.rs
- lychee-lib/src/types/uri.rs
* Strip `.git` suffix from Github URLs (#384)
* Strict handling of non-existent files inside public Github repos (#449)
* Add more false-positives to the list of Github endpoints, which will be ignored from the API checking.
* Only accept two path segments (org/repo) for Github API check if repo is public
> Improve Github API usage

- Cargo.lock
- README.md
- examples/builder/builder.rs
- lychee-bin/Cargo.toml
- lychee-bin/src/cache.rs
- lychee-bin/src/commands/check.rs
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/src/parse.rs
- lychee-bin/src/stats.rs
- lychee-bin/src/time.rs
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/extract/mod.rs
- lychee-lib/src/helpers/path.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/cache.rs
- lychee-lib/src/types/mod.rs
- lychee-lib/src/types/status.rs
- lychee-lib/src/types/uri.rs
A while ago, caching was removed due to some issues (see https://github.com/lycheeverse/lychee/pull/349).
This is a new implementation with the following improvements:
* **Architecture**: The new implementation is decoupled from the collector, which was a major issue in the last version. Now the collector has a single responsibility: collecting links. This also avoids race-conditions when running multiple `collect_links` instances, which probably was an issue before.
* **Performance**: Uses DashMap under the hood, which was noticeably faster than `Mutex<HashMap>` in my tests.
* **Simplicity**: The cache format is a CSV file with two columns: URI and status. I decided to create a new struct called `CacheStatus` for serialization, because trying to serialize the error kinds in `Status` …
> Add caching functionality (v2)

- lychee-lib/src/extract/html.rs
When URLs couldn't be extracted from a tag,
we ran a plaintext search, but never added the
newly found urls to the vec of extracted urls.
Also tried to make the code a little more idiomatic
> Fix bugs in extractor; reduce allocs

- Cargo.lock
- Cargo.toml
- lychee-bin/Cargo.toml
- lychee-bin/src/options.rs
This commit replaced the use of `lazy_static` by
`const_format` in `lychee-bin`.
Currently `lazy_static` is used to generate static
String at runtime. With `const_format` we can instead
make constant String at compile time.
> lychee-bin: replace lazy_static by const_format

- lychee-bin/src/commands/check.rs
In other issues I've already lamented how slow lychee is when used
without `-n`. This fixes an issue where without `-n`, lychee would take
1 minute instead of 4 seconds to check sentry-docs.
> fix constant updating of progressbar

- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/uri.rs
This commit mainly added or improved documentation for `lychee-lib::client`
module.
But it also contains a few API changes:
- `ClientBuilder::client()` now consumes itself instead of taking a reference.
This helps to avoid a few unnecessary clones.
- `ClientBuilder::build_filter()` was a private function and is inlined to avoid
unnecessary clones.
- Added a new crate-socped function `Uri::set_scheme()`.
> lychee-lib::client reworked

- README.md
- examples/client_pool/client_pool.rs
- examples/extract/extract.rs
- lychee-bin/src/commands/check.rs
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/main.rs
- lychee-bin/src/writer/compact.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/quirks/mod.rs
- lychee-lib/src/types/input.rs
- lychee-lib/src/types/mail.rs
Makes for arguably cleaner-looking code.
The downside is that the MSRV is 1.58
https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html
Given that nobody uses lychee as a library yet
and we have precompiled binaries, it's an acceptable
tradeoff.
My little research revealed that this is a much-liked
feature: https://twitter.com/matthiasendler/status/1483895557621960715
> Use captured identifiers in format strings

- lychee-bin/src/commands/check.rs
- lychee-bin/src/writer/detailed.rs
- lychee-bin/tests/cli.rs
- lychee-bin/tests/local_files.rs
- lychee-lib/src/client.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/helpers/path.rs
- lychee-lib/src/helpers/request.rs
- lychee-lib/src/types/base.rs
- lychee-lib/src/types/cache.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/input.rs
- lychee-lib/src/types/response.rs
- lychee-lib/src/types/status.rs
- lychee-lib/src/types/uri.rs
After reading ["Context-preserving error handling"](https://kazlauskas.me/entries/errors) by @nagisa, I realized that we were dropping a lot of the error context when creating errors with `?`. Instead, this PR tries to avoid `?` and `.into()` in the lib where a `map_err` would preserve and encapsulate context. (See code for examples.)
Along the way, the following changes were made:
* Remove tautological "Error" suffix from `ErrorKind` variants.
* Avoid generic error kinds in favor of more granular ones to preserve the context of what error occurred exactly. 
* Remove all boxing of underlying errors.
The fact that we can avoid boxing error altogether was a convenient side-effect of restructuring the error kinds.
> Error cleanup

- lychee-bin/src/cache.rs
- lychee-bin/src/stats.rs
- lychee-lib/src/types/cache.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/response.rs
- lychee-lib/src/types/status.rs
This changes the way we print responses.
Before, the response and status were concatenated, e.g.
```
https://github.com/fooFail [cached].
```
This is a regression from #510.
Now there is a colon and a space in between the URL and the status and the status code is prepended
```
https://github.com/foo: Fail [cached]
```
In fact, the output is cleaner now in general.
The full output is
```
↻ [404] https://github.com/foo: Fail (cached)
```
(The status code is always in front; the explanation got shortened to the relevant parts without being too verbose)
For successes it looks like this:
```
✔ [200] https://smartbear.com/: OK
```
...and for non-cached errors
```
✗ [404] https://www.defensecode.com/web-security-scanner-dast/: Network error: Not Found
```
If there is no status code, we print a …
> Response output overhaul

- README.md
- lychee-bin/src/client.rs
- lychee-bin/src/options.rs
- lychee-bin/src/parse.rs
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
This was always hardwired to 1 second until now, but it makes sense to make it configurable.
See #474.
> Make retry wait time configurable

- lychee-bin/src/commands/check.rs
- lychee-bin/src/main.rs
- lychee-lib/src/types/input.rs
Make sure that broken pipes (e.g. when a reader of a
pipe prematurely exits during execution) get handled gracefully.
This change also moves some error messages to stderr by using
eprintln.
More info: https://github.com/jez/as-tree/issues/15
> Fix broken pipe error on failing writes to stdout

- lychee-bin/src/main.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/status.rs
Print original reqwest error for every Github link.
It contains more information about the underlying error.
Only print a message about the Github token at the
end if it's not set and there were Github errors.
> Print Github token error once at the end

- lychee-lib/src/client.rs
Temporary workaround for https://github.com/lycheeverse/lychee/issues/539 until the issue gets fixed upstream.
> Avoid reqwest panic on invalid URIs

- lychee-lib/src/extract/plaintext.rs
Immediately return for very small strings which cannot be valid URIs.
The shortest valid URI without a scheme might be g.cn (Google China)
At least I am not aware of a shorter one. We set this as a lower threshold
for parsing URIs from plaintext to avoid false-positives and as a slight
performance optimization, which could add up for big files.
This threshold might be adjusted in the future.
> Optimize plaintext extractor for small strings

- README.md
- benches/src/extract.rs
- examples/extract/extract.rs
- fixtures/TEST_CODE_BLOCKS.md
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/extract/html.rs
- lychee-lib/src/extract/html5ever.rs
- lychee-lib/src/extract/html5gum.rs
- lychee-lib/src/extract/markdown.rs
- lychee-lib/src/extract/mod.rs
This adds support for ignoring Markdown code blocks with `--skip-code-blocks`.
We should make this the default at some point, but I'm not sure if we should do it right away.
I doubt that anyone currently depends on checking links inside code blocks, though.
I added this to the pulldown_cmark extractor to avoid unnecessary
allocations. The same can be done for the HTML extractor in the future.
I'm wondering if we should stick to our established nomenclature and rename
`--skip-code-blocks` to `--exclude-code-blocks`.
Or, even better, implement that functionality for HTML, too, so we can use something like
`--exclude-elements code,pre`. (This won't work for plaintext of course and will be ignored, which we should document in the help output.)
> Implement excluding code blocks

- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/types/input.rs
This requires `Input::new` to return a `Result`, because the URL
parsing could fail when prepending `http://`.
We use http instead of https, because curl does as well:
https://github.com/curl/curl/blob/70ac27604a2abfa809a7b2736506af0da8c3c8a9/lib/urlapi.c#L1104-L1124
> Allow input URLs without scheme (fixes #567)

- lychee-bin/src/commands/check.rs
- lychee-lib/src/types/status.rs
Don't print cached status output when not in verbose mode
> Cache verbosity issue (fixes #562)

- fixtures/bench/.gitignore
- lychee-lib/src/helpers/mod.rs
- lychee-lib/src/helpers/reqwest.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/response.rs
- lychee-lib/src/types/status.rs
Recently we cleaned up the commandline output to trim away redundant
information like the URL, which occured twice.
Unfortunately we also removed helpful information from reqwest, which
could support the user in troubleshooting unexpected errors.
This commit reverts that.
We now extract the meaningful information from reqwest, without being
too verbose. For that we have to depend on the string output for the
reqwest error, but it's better than hiding that information from the user.
It is fragile as it depends on the reqwest internals, but in the worst case
we simply return the full error text in case our parsing won't work.
> Extract more status information from reqwest

- .github/workflows/docker.yml
Since github.repository_owner refers to the base repository on pull request events, while secrets need to exist on the head repository, the Docker Hub login fails for pull requests opened from forks. This commit assures that this step in case of pull request events only runs for internal pull requests, i.e. when head and base repository are the same.
For the actual Docker Hub upload, no change is required: The build can run in every case, the upload is not done on pull request events in general.
> Skip Docker login on PRs from forks

- Cargo.lock
- lychee-lib/src/client.rs
- lychee-lib/src/extract/plaintext.rs
Skipping to parse very short strings was merged into linkify
so our own workaround is unnecessary
https://github.com/robinst/linkify/pull/34
> Move to downstream optimization for short strings

- lychee-lib/src/client.rs
This sets a HTTP connect timeout (for stability)
and a TCP keepalive (for performance).
The connect timeout should help with flaky servers, which
would block the runtime and therefore other requests.
The keepalive helps when making many requests to the same
host. This is a very common pattern for checking internal documentation,
which is an important use-case of lychee.
The settings are currently not configurable by the user
and set to sane defaults. We might make this configurable in the future
if there is demand to do so.
Fixes #569.
> Extend reqwest client settings

- fixtures/ignore/.lycheeignore
- fixtures/ignore/TEST.md
- lychee-bin/src/main.rs
- lychee-bin/tests/cli.rs
Lines starting with the comment character (`#`) inside the
.lycheeignore file will be ignored.
Whitespace at the beginning of each line will be ignored, so
even an indented comment character will work.
```markdown
.*\.example.com
example.org/.+
http://.*
#https://example.net
github.com/.*/.*$
^file.*
@
```
Fixes #585.
> Add support for comments in `.lycheeignore`

- fixtures/TEST_DUMP_EXCLUDE.txt
- lychee-bin/src/commands/dump.rs
- lychee-bin/tests/cli.rs
This is a minimally invasive version, which allows to grep for `[excluded]`.
The reason for exclusion would require more work and it's debatable if
it adds any value, because it might make grepping harder and the source
of exclusion is easily deducatable from the commandline parameters
or the `.lycheeignore` file.
Excluded links will only printed in verbose mode.
Example:
```
> lychee --exclude github --dump --verbose -- README.md
...
https://rustup.rs/ (README.md)
file:///Users/mendler/Code/private/lychee/lychee/assets/logo.svg (README.md)
https://github.com/pingcap/docs (README.md) [excluded]
https://github.com/raviqqe/liche/issues/13 (README.md) [excluded]
https://docs.rs/lychee-lib (README.md)
...
```
Fixes #587.
> Also dump excluded links

- Cargo.lock
- README.md
- examples/collect_links/collect_links.rs
- fixtures/exclude-path/dir1/TEST.md
- fixtures/exclude-path/dir2/TEST.md
- fixtures/exclude-path/dir2/subdir/TEST.md
- lychee-bin/Cargo.toml
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/helpers/path.rs
- lychee-lib/src/types/input.rs
This change deprecates `--exclude-file` as it was ambiguous.
Instead, `--exclude-path` was introduced to support excluding paths
to files and directories that should not be checked.
Furthermore, `.lycheeignore` is now the only way
to exclude URL patterns.
Fixes https://github.com/lycheeverse/lychee/issues/418.
> Add support for excluding paths from link checking

- README.md
- lychee-bin/src/client.rs
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/options.rs
- lychee-bin/src/parse.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/remap.rs
- lychee-lib/src/types/error.rs
Allow users to remap URIs. Regular expressions are supported. Remappings get evaluated in order of definition. Multiple remappings are allowed.  
The format is similar to that of `markdown-link-check`.
Consider the following input:
```markdown
file://../../issues
https://example.com
https://example.org
https://example.net
```
Let's remap these inputs using the `--remap` parameter:
```sh
lychee --remap 'https://example.com http://127.0.0.1:8080' \
--remap 'https://example.org https://staging.example.com' \
--remap '../../issues https://github.com/usnistgov/OSCAL/issues' \
-- input.md
```
This would check the following URIs:
```
https://github.com/usnistgov/OSCAL/issues
http://127.0.0.1:8080/
https://staging.example.com/
https://example.net/
```
* Be careful when using this feature because …
> Add support for URI remapping

- fixtures/TEST_EXAMPLE_DOMAINS.md
- lychee-bin/Cargo.toml
- lychee-bin/tests/example_domains.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/filter/mod.rs
This skips example domains from checking.
I decided to not make this configurable by the user and instead always
skip example domains except while running tests.
Unfortunately, it's not possible to automatically enable features
for `cargo test`. See https://github.com/rust-lang/cargo/issues/2911.
As a workaround to allow for using example domains for unit- and integration
tests,  we introduce a new feature, `check_example_domains`, which is
disabled by default for normal users. The feature gets activated for the
integration test which checks that the example domain exclusion works as
expected.
Closes https://github.com/lycheeverse/lychee/issues/551.
> Exclude example domains as per RFC 2606 from checking

- lychee-lib/src/extract/mod.rs
llvm will typically create much faster code than accessing a hashset at
runtime
~source: trust me bro~ actually ran benchmarks now
> Replace lazy hashset with matches!

- lychee-bin/src/commands/check.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/types/cache.rs
- lychee-lib/src/types/status.rs
As discussed in https://github.com/lycheeverse/lychee/issues/647#issuecomment-1170773449, it does not make much sense to cache unsupported
and excluded URLs.
Unsupported URLs might be supported in the future and caching them
would mean they won't get checked then. Excluded URLs were
excluded for a reason and should not appear in the cache.
Furthermore they might not be excluded
in a consecutive run, leading to a false-positive.
> Skip caching unsupported and excluded URLs

- .github/workflows/docker.yml
See: https://github.com/peter-evans/dockerhub-description/issues/10
Bump GH actions versions.
As a reminder, we already discussed this in https://github.com/lycheeverse/lychee/pull/325
> Update description with token now supported

- lychee-bin/tests/cli.rs
- lychee-lib/src/types/input.rs
Update `Input::new` to immediately exit when the input is a relative path that does not exist. The early return helps guarantee the input is not coerced into a URL that will take 30 seconds to resolve.
Also adds a small test to validate the new behavior.
I tried to follow the guidance from this comment when resolving the issue: https://github.com/lycheeverse/lychee/issues/666#issuecomment-1172172797
> Update to gracefully handle nonexistent relative paths

- lychee-bin/src/formatters/stats/markdown.rs
As mentioned in #694, this is a first simple and quick improvement to the md output that brings it more in line with what is shown in the console and helps with spotting the error type.
Until there is agreement on a new, better and uniform style and somebody has time to implement that, this should be a little improvement in the meantime.
old:
- [mre/idiomatic-rust-doesnt-exist-man](https://github.com/mre/idiomatic-rust-doesnt-exist-man): Failed: Network error (status code: 404)
new:
- [404] [mre/idiomatic-rust-doesnt-exist-man](https://github.com/mre/idiomatic-rust-doesnt-exist-man) | Failed: Network error
<br>
I hope I got it right. :)
> Reorder md output

- README.md
The repo [InnerSourceCommons/InnerSourcePatterns](https://github.com/InnerSourceCommons/InnerSourcePatterns) is using lychee as a link checker since a couple of days.
(we found the recommendation for it in the liche repo)
I wasn't clear if we should add the new user/repo at top or bottom of the list.
Went for the top :)
Thank you for this great tool!
> Listing InnerSourceCommons/InnerSourcePatterns as user

- Cargo.lock
- README.md
- lychee-bin/Cargo.toml
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
Structopt was subsumed by clap. See
https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating
I think the help output looks much cleaner now (and has colors! ✨).
> Move from structopt to clap

- README.md
- fixtures/configs/smoketest.toml
- lychee-bin/src/options.rs
- lychee.example.toml
Having this help available:
```
$ lychee --help
[...]
--exclude <exclude>...                 Exclude URLs from checking (supports regex)
[...]
--exclude-mail           Exclude all mail addresses from checking
[...]
```
makes me think "How to I exclude single email addresses?".
The answer is: `--exclude` does this as well.
For me, this was not clear from the start.
This pull requests changes the help text for the `--exclude` argument from
> Exclude URLs from checking (supports regex)
to
> Exclude URLs and mail addresses from checking (supports regex)
> Extend description of "--exclude" to also exclude email addresses, not only URLs

- README.md
- lychee-bin/tests/usage.rs
The help message was highlighted as if it was a gitignore file.
Let's disable this spurious syntax highlighting.
> Fix syntax highlighting in README

- Cargo.lock
- docs/TROUBLESHOOTING.md
- examples/builder/builder.rs
- fixtures/TEST_EMAIL_QUERY_PARAMS.html
- fixtures/TEST_EMAIL_QUERY_PARAMS.md
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/filter/mod.rs
- lychee-lib/src/helpers/path.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/input.rs
- lychee-lib/src/types/mail.rs
- lychee-lib/src/types/uri/valid.rs
Email addresses with query parameters often get used in
contact forms on websites. They can also be found in
other documents like Markdown.
A common use-case is to add a subject line to the email
as a parameter e.g. `mailto:mail@example.com?subject="Hello"`.
Previously we handled such cases incorrectly by interpreting
them as files. The reason was that our email parsing was too strict
to allow for query parameters at the end of an email address.
With [email_address] we switched to a more permissive parser.
Note that this does not affect the actual address email _checking_,
as this is still done with [check-if-email-exists], which has more strict
check functionality. For the check we pass the path to `check-if-email-exists`
and ignore the query params because they aren't part the email …
> Fix parsing error of email addresses with query params

- fixtures/TEST_EXAMPLE_DOMAINS.md
- lychee-bin/tests/example_domains.rs
- lychee-lib/src/filter/mod.rs
- lychee-lib/src/types/uri/valid.rs
This was an oversight so far that became apparent after our
recent fix for email addreses with query params
(e.g. `test@example.com?subject=test`).
The parsing of email addresses has improved and so we detect
more mail addresses, but we didn't check if they belonged
to an example domain, causing false-positive checks.
> Don't check example mail addresses by default

- Cargo.lock
- README.md
- fixtures/TEST_DATA_URIS.html
- lychee-bin/Cargo.toml
- lychee-bin/src/commands/check.rs
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/src/verbosity.rs
- lychee-bin/tests/data_uris.rs
- lychee-lib/src/types/uri/valid.rs
More granular verbosity levels have been asked
for repeatedly.
To enable that we're moving to [env_logger] and [clap-verbosity-flag]
to provide more flexible verbosity settings.
Also tackles #661, #709.
Lays the groundwork for tackling #268 and #704.
https://github.com/rust-cli/env_logger
https://github.com/clap-rs/clap-verbosity-flag
> Add different verbosity levels

- lychee-lib/src/collector.rs
- lychee-lib/src/extract/html5ever.rs
- lychee-lib/src/extract/html5gum.rs
- lychee-lib/src/extract/mod.rs
This is a naive approach to exclude script tags from getting checked. The reason is that the tag leads to a lot of false-positives (e.g. `//unpkg.com/docsify-edit-on-github@1` within a script block gets detected as an e-mail address).
A more thorough approach would be the use of a tree-builder in html5gum and html5ever, but this could have a negative performance impact.
I also did not want to add a new flag (e.g. `--include-scripts`) for this setting because the current set of flags around exclusion/inclusion is already quite long.
Fixes #821.
> Exclude <script> tags by default

- lychee-bin/src/formatters/duration.rs
- lychee-bin/src/formatters/mod.rs
- lychee-bin/src/main.rs
Previously the cache age was formatted with nanosecond resolution,
which is too fine-grained even for Rustaceans.
Now the format is limited to days, hours, minutes, and seconds.
With that, the cache age becomes more easily parseable by humans.
> Less verbose cache age formatting

- lychee-lib/src/extract/html5ever.rs
- lychee-lib/src/extract/html5gum.rs
- lychee-lib/src/extract/mod.rs
This handles cases like
```html
<code>
<pre>
<span>https://example.org</span>
</pre>
</code>
```
where a link was embedded in a verbatim block, but embedded in a non-verbatim element (`<span>`).
This was correctly handled in html5ever, but not html5gum (which is our default HTML parser in lychee)
Fixes https://github.com/lycheeverse/lychee/issues/259#issuecomment-1328292006.
@untitaker, is there a better way to handle nested tags in html5gum or would you have resolved the issue in a similar way?
> Recursively skip verbatim elements

- lychee-bin/src/commands/check.rs
- lychee-bin/src/formatters/stats/compact.rs
- lychee-bin/src/formatters/stats/detailed.rs
- lychee-bin/src/formatters/stats/markdown.rs
- lychee-bin/src/stats.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/status.rs
Fixes #268.
Adds support for successful and excluded URLs.
Also,
* added missing `PartialEq` impls for `ErrorKind` variants
* fixed counters
* removed `failure`, as it was redundant; merged with `errors`
> Extend response stats in verbose mode

- fixtures/TEST_VERBATIM.html
- lychee-bin/tests/cli.rs
- lychee-lib/src/extract/mod.rs
- lychee-lib/src/test_utils.rs
- lychee-lib/src/types/file.rs
Previously remote URLs were incorrectly detected because the
string representation of a path is different than the path itself,
causing the `http` prefix match to be insufficient.
This resulted in unexpected side-effects, such as the
incorrect detection of verbatim mode for remote URLs.
The check now got improved and unit tests were added to avoid
future breakage. On top of that, missing verbatim elements were added.
Fixes #895.
> Harden URL detection and extend verbatim elements

- lychee-bin/src/commands/dump.rs
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/remap.rs
- lychee-lib/src/types/error.rs
`lychee_lib::client`:
- Improved documentation.
- Added an log message in `ClientBuilder::client()` when provied user-agent
overrides the one defined in provied custom header.
- Removed unnecessary error handling in `Client::check()` when setting HTTPS
scheme because all failure cases should occur when checking this URL the first
time already.
- Removed unnecessary error handling in `Client::remap()` since
`lychee-lib::remap::Remaps::remap()` doesn't returns a `Result` anymore.
- Fixed potential integer overflow in `Client::check_website()` when the wait
time between retries doubles, by using `std::time::Duration::saturating_mul`
instead.
- Renamed `invalid()` to `validate_url()`.
`lychee_lib::remap`:
- Improved documentation, in particular, clarified (in the comment) that it's
URLs not …
> chore!: improve client and remap modules

- .github/workflows/ci.yml
I don't see the reason why publish-check has to wait for the other jobs to complete. After all, it's yet another "lint". Running it in parallel might shave of a significant amount of time from our CI builds.
> Run publish-check in parallel with other jobs

- Cargo.lock
- README.md
- examples/builder/Cargo.toml
- examples/client_pool/Cargo.toml
- examples/collect_links/Cargo.toml
- examples/extract/Cargo.toml
- examples/simple/Cargo.toml
- lychee-bin/Cargo.toml
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/types/status.rs
Assert that code 200 never needs to be explicitly accepted for cached response
to match the behavior of uncached checks.
Immediately bumps the version to 0.11.1 for the hotfix.
See discussion in #843.
> Fix cached 200 status code handling

- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/status.rs
Having more than the max number of redirects
caused lychee to abort the requests, but did not
lead to an error.
https://github.com/lycheeverse/lychee-action/issues/164
> Fix `--max-redirects`

- Cargo.lock
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/retry.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/uri/valid.rs
Previously, lychee would blindly retry all requests,
no matter if the request error was transient or fatal.
Taking a lesson from https://github.com/TrueLayer/reqwest-middleware,
we can be more granular about the error behavior.
This PR adds their retry logic to lychee, reducing the number of
unnecessary requests significantly.
I also made some ergonomic changes to the client, which should not
affect its behavior.
> Better retry handling

- .github/workflows/ci.yml
- Makefile
- fixtures/TEST_VERBATIM.html
- lychee-bin/tests/cli.rs
- lychee-lib/src/extract/html5ever.rs
- lychee-lib/src/extract/html5gum.rs
Skipping URLs in verbatim elements didn't take nested
elements into consideration, which were not verbatim.
For instance, the following HTML snippet would yield
`https://example.com` in non-verbatim mode, even if
it is nested inside a verbatim `<pre>` element:
```html
<pre><a href="https://example.com">link</a></pre>
```
This commit fixes the behavior for both `html5gum` and
`html5ever`.
Note that nested verbatim elements of the same kind
still are not handled correctly.
For instance,  the following HTML snippet would still yield
`https://example.com`:
```html
<pre>
<pre></pre>
<a href="https://example.com">link</a>
</pre>
```
The reason is that we currently only keep track of a single
verbatim element and not a stack of elements, which we
would need to unwind and resolve the situation. …
> Fix nested URL extraction in verbatim elements

- Cargo.lock
- lychee-bin/src/formatters/stats/markdown.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/types/response.rs
- lychee-lib/src/types/status.rs
This is the PR regarding to the previous discussion about the status code in the fail_map and success_map (https://github.com/lycheeverse/lychee/discussions/1013).
`cargo run -- www.example.com --format json -v` now prints a success_map, containing a status object with a text and a code field. 
The code field is not included, when the status doesn't contain a code.
```
..., 
"success_map": {
"http://www.example.com/": [
{
"url": "https://www.iana.org/domains/example",
"status": {
"text": "OK (200 OK)",
"code": 200
}
}
]
},
...
```
> Status codes in maps

- lychee-bin/src/commands/check.rs
- lychee-bin/tests/cli.rs
- lychee-bin/tests/local_files.rs
Fixes https://github.com/lycheeverse/lychee/issues/984
From https://doc.rust-lang.org/book/ch12-06-writing-to-stderr-instead-of-stdout.html:
> Command line programs are expected to send error messages to the standard error stream so we can still see error messages on the screen even if we redirect the standard output stream to a file. Our program is not currently well-behaved: we’re about to see that it saves the error message output to a file instead!
> Use standard error for error output

- lychee-lib/src/client.rs
Perform a warm-up request to ensure the lazy regexes in `lychee-lib/src/quirks/mod.rs` are compiled. On some platforms, this can take some time(approx. 110ms), which should not be counted in the test.
Additional context: I am packaging lychee for RISC-V archlinux and this test fails.
> fix(test): perform a warm up request in test_exponential_backoff

- Cargo.lock
- lychee-bin/Cargo.toml
- lychee-bin/src/commands/check.rs
- lychee-bin/src/stats.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/input.rs
This adds a new field, `duration_secs` to the JSON report:
```json
{
"total": 55,
"successful": 55,
"unknown": 0,
"unsupported": 0,
"timeouts": 0,
"redirects": 0,
"excludes": 0,
"errors": 0,
"cached": 0,
"success_map": {},
"fail_map": {},
"suggestion_map": {},
"excluded_map": {},
"duration_secs": 1,
"detailed_stats": false
}
```
It's helpful for troubleshooting slow runs and for measuring the performance over time.
> Add check duration (in seconds) to report

- lychee-bin/Cargo.toml
This PR updates the `Cargo.toml` of `lychee` to add [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall) metadata as mentioned in https://github.com/lycheeverse/lychee/issues/59#issuecomment-1555966155
Tested as follows:
```
$ cargo binstall lychee --manifest-path lychee-bin/Cargo.toml --dry-run
INFO resolve: Resolving package: 'lychee'
WARN The package lychee v0.13.0 will be downloaded from github.com
INFO This will install the following binaries:
INFO   - lychee (lychee -> /home/orhun/.cargo/bin/lychee)
INFO Dry-run: Not proceeding to install fetched binaries
INFO Done in 4.958623872s
```
> Add metadata for cargo-binstall

- .github/dependabot.yml
- .github/workflows/docker.yml
- Dockerfile-CI.Dockerfile
- Dockerfile-CI.alpine.Dockerfile
- README.md
Do not see any issue for this, but somehow it may be related to https://github.com/lycheeverse/lychee/issues/59 :)
- docker: add alpine flavor for CI docker image
- reduces image from ~37 MB (debian) to ~12 MB on the registry side (compressed)
- reduces image from ~104 MB (debian) to ~30 MB on the local disk (uncompressed)
- security: run lychee as non-root user for alpine
- docs: add example about running lychee on Windows PowerShell
- docs: add `--rm` flag to docker run command to remove container after the run (self-cleanup)
- docs: add `-w /input` flag to docker run command to set working directory to /input
- better UX when running lychee from docker locally (feeling like cli)
- ci: tag/build/push for alpine
bonus:
- docker related github-actions: bump (because of …
> alpine for docker image

- lychee-lib/src/client.rs
This test is still flaky on riscv64 boards after #1049.
It turns out that building the client might take 59ms, which should not be counted.
> test(client): make exponential_backoff better

- lychee-bin/src/formatters/stats/compact.rs
The error details in the compact report are computed incorrectly.
This leads to weird output, as shown in the screenshot.
Since the information is misleading, and we show a list of errors anyway, the safest way to fix this bug is to get rid of the detailed stats.
> Remove inaccurate details in compact view

- lychee-bin/src/commands/check.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/status.rs
Unknown status codes should be skipped and not cached by default. The reason is that we don't know if they are valid or not and even if they are invalid, we don't know if they will be valid in the future.
The only error case I know of is currently LinkedIn, which returns a `999` status code.
> Don't cache unknown status codes

- Cargo.lock
- README.md
- benches/Cargo.toml
- examples/builder/Cargo.toml
- examples/client_pool/Cargo.toml
- examples/collect_links/Cargo.toml
- examples/extract/Cargo.toml
- examples/simple/Cargo.toml
- lychee-bin/Cargo.toml
- lychee-bin/src/main.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/mail.rs
Hello. I would like to discuss adding optional [Rustls](https://github.com/rustls/rustls) support to Lychee. I've prepared a pull request to show that's it's mostly a question of passing feature flags down to existing dependencies. What do you think?
---
This commit adds a non-default feature flag to use Rustls instead of OpenSSL.
My personal motivation is to use Lychee on OpenBSD -current, where the `openssl` crate frequently fails to link against the unreleased system LibreSSL. Using the `vendored-openssl` feature helps with compilation, but segfaults at runtime.
The commit adds three feature flags to the library, binary, benchmark, and all examples:
- The `native-tls` feature flag toggles the `openssl` crate.
- The `rustls-tls` feature flag toggles the `rustls` crate.
- The …
> Add optional Rustls support

- lychee-lib/src/client.rs
This adds a custom redirect policy,
which logs redirects as debug messages.
It can help with troubleshooting, e.g. in situations like https://github.com/lycheeverse/lychee/issues/1115.
@oupala fyi
> Log redirects in verbose mode (-vv)

- Makefile
- fixtures/configs/smoketest.toml
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/parse.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
- lychee-lib/src/remap.rs
- lychee-lib/src/types/error.rs
Extend support for remapping
This adds support for partial remaps and
capture groups to the remap feature.
Fixes #1129
> Extend remap feature

- lychee.example.toml
I think the regex was wrong and it should be like that. it is also used in `include = [ 'gist\.github\.com.*' ]` some lines below.
> fix exclude pattern in example

- .gitignore
- Cargo.lock
- Makefile
- README.md
- lychee-bin/Cargo.toml
- lychee-bin/src/client.rs
- lychee-bin/src/commands/check.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/src/parse.rs
- lychee-bin/tests/cli.rs
- lychee-lib/Cargo.toml
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/cookies.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/mod.rs
This is a very conservative and limited implementation of cookie support.
The goal is to ship an MVP, which covers 80% of the use-cases.
When you run lychee with `--cookie-jar cookies.json`, all cookies will be stored in `cookies.json`, one cookie per line.
This makes cookies easy to edit by hand if needed, although this is an advanced use-case and the API for the format is **not** guaranteed to be stable.
My initial goal was to use the same cookie file format that curl uses, but I backed away from this thought for a few reasons:
* The cookie file format is an implementation detail: people should not rely on the format to never change.
* There is on Rust implementation for the curl format out there, so we'd have to roll our own, test it, and maintain it, which sounds like unnecessary …
> Cookie Support

- README.md
- lychee-bin/src/commands/dump.rs
- lychee-bin/src/commands/mod.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/types/input.rs
Fixes #684
This PR adds support for the CLI flag `--dump-inputs` which prints out input sources without collecting and checking links.
> feat: Add support for --dump-inputs

- README.md
- fixtures/TEST_EMAIL.md
- fixtures/TEST_EXCLUDE_1.txt
- fixtures/TEST_EXCLUDE_2.txt
- lychee-bin/src/client.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-bin/tests/example_domains.rs
- lychee-lib/src/client.rs
- lychee-lib/src/filter/mod.rs
- lychee.example.toml
E-Mail checks cause too many false-postives,
so we put them behind a flag.
* `--exclude-mail` is deprecated (to be removed in 1.0)
* `--include-mail` is the new flag
This PR also removes the obsolete tests for `--exclude-file`, which was superseded by `.lycheeignore`.
Fixes #1089
> Make checking email addresses optional

- lychee-lib/src/extract/html/html5ever.rs
- lychee-lib/src/extract/html/html5gum.rs
- lychee-lib/src/extract/html/mod.rs
- lychee-lib/src/extract/html/srcset.rs
- lychee-lib/src/extract/markdown.rs
- lychee-lib/src/extract/mod.rs
Our current `srcset` parsing is pretty basic.
We split on comma and then on whitespace and take the first part, which is the image source URL.
However, we don't handle URLs containing unencoded commas like
`/cdn-cgi/image/format=webp,width=640/https://img.youtube.com/vi/hVBl8_pgQf0/maxresdefault.jpg`, which leads to false-positives.
According to the spec, [commas in strings should be encoded](https://developers.google.com/maps/url-encoding), but in practice, there are some websites which don't do that. To handle these cases, too, I propose to extend the `srcset` parsing to make use of a small "state machine", which detects if a comma is within the image source or outside of it while parsing.
This is part of an effort to reduce false-positives during link checking.
> Improve `srcset` parsing

- .github/workflows/ci.yml
The '! cargo tree -i openssl-sys' command ignores when 'cargo tree'
fails for other reasons than not depending on the openssl-sys crate.
This commit changes the command to propagate such a failure.
> Improve 'cargo tree' check

- .github/workflows/nightly.yml
- As we discussed in https://github.com/lycheeverse/lychee/pull/1133#issuecomment-1669290206
This action will check if it has changes compared to the last nightly release, if so, it will delete the last nightly release and create a new one.
> Add nightly release

- .github/workflows/nightly.yml
There are two errors in the past nightly CI:
- https://github.com/lycheeverse/lychee/actions/runs/5876633509/job/15935180970
- because the `gh release delete --cleanup-tag`  won't delete the local tag, refer to https://github.com/cli/cli/blob/4a57a812f5db9db72812030f19b214c93b18b297/pkg/cmd/release/delete/delete.go#L136
- https://github.com/lycheeverse/lychee/actions/runs/5888738531/job/15970534873
- because the previous nightly CI deleted the remote tag & release but failed to generate a new one
This PR should fix them. It will detect if the `nightly` tag exists:
- exist: check if there are new commits
- not exist: release a new `nightly`
> fix nightly release bash script

- lychee.example.toml
These two websites as usually not checked.
Resolves #1233
> Add sensible excluded URL-s to lychee.example.toml

- fixtures/fragments/file.html
- fixtures/fragments/file1.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/extract/html/html5gum.rs
- lychee-lib/src/extract/html/mod.rs
- lychee-lib/src/extract/markdown.rs
- lychee-lib/src/extract/mod.rs
- lychee-lib/src/utils/fragment_checker.rs
Part of the https://github.com/lycheeverse/lychee/issues/185 work.
This PR adds fragment checking for the second type of link in https://github.com/lycheeverse/lychee/issues/185#issuecomment-1613580697 .
> Check fragments in HTML files

- lychee-lib/src/filter/mod.rs
> Exclude URLs ending with xmlrpc.php

- README.md
Add missing exit code to the README.md
Corresponding `enum` in `main.rs`
```rust
enum ExitCode {
Success = 0,
UnexpectedFailure = 1,
LinkCheckFailure = 2,
ConfigFile = 3,
}
```
> Update README.md with exit code 3

- lychee-bin/src/formatters/stats/markdown.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/extract/mod.rs
- lychee-lib/src/test_utils.rs
- lychee-lib/src/types/uri/valid.rs
With Rust 1.73 and 1.74 [new lints were added to clippy](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-174). Some of these new lints caused new warnings and the linting step to fail.
> Address warnings of the new clippy lints

- README.md
[Bencher](https://github.com/bencherdev/bencher) uses Lychee to check links in CI. Thank you!
> Add Bencher to Lychee users list

- fixtures/TEST_EXAMPLE_DOMAINS.md
- fixtures/TEST_EXAMPLE_DOMAINS_FALSE_POSITIVES.md
- lychee-bin/tests/example_domains.rs
- lychee-lib/src/filter/mod.rs
Websites like https://gobyexample.com were incorrectly classified as example domains as defined by IETF.
Related to #1312.
> Fix false-positive example domains

- .github/workflows/release.yml
- lychee-lib/src/types/input.rs
Dear @mre ,
I've noticed the release workflow was not updated since long time and I think we are missing proper token permissions for uploading release assets. Please take a look and I hope you will like it.
Cheers,
Arek
> ci: fix missing permissions for uploading release assets

- fixtures/fragments/file1.md
- fixtures/fragments/file2.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/utils/fragment_checker.rs
The `Url` struct percent escapes fragments which breaks checks for titles containing utf8 characters.
This PR has a test for this eventuality and a suggested bug fix.
> Decode percent escapes in fragments

- lychee-bin/tests/cli.rs
google.com might redirect to other domains, causing cookie_jar test to fail.
Sample:
```
builduser@kxxt lychee-0.14.0]$ target/release/lychee "--cookie-jar" jar - <<< "https://google.com"
1/1 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links
🔍 1 Total (in 0s) ✅ 1 OK 🚫 0 Errors
[builduser@kxxt lychee-0.14.0]$ cat jar
{"raw_cookie":"1P_JAR=2024-01-06-04; Secure; Path=/; Domain=google.com; Expires=Mon, 05 Feb 2024 04:44:48 GMT","path":["/",true],"domain":{"Suffix":"google.com"},"expires":{"AtUtc":"2024-02-05T04:44:48Z"}}
{"raw_cookie":"NID=511=GCIi5CLLPHfAgf24gPz2pdzw2eiM-gqKpgG2uplUc3umyqYIkO5llBy-73aJLHZpm9QR1Bw2lArzpMGY10ef0b7VfXj2UB5ravYbpXq7RBR4RefOxx0et6UVc7-4YqcGW9QslF9tpykeF-H4XYyO7pZWioGqAUtP4fe8v-ns3LE; HttpOnly; Path=/; Domain=google.com; Expi
res=Sun, 07 Jul 2024 04:21:33 …
```
> fix(test_cookie_jar): use google.com/ncr

- lychee-bin/src/options.rs
> fix: Add accept option to merged config

- lychee-lib/Cargo.toml
- lychee-lib/src/types/accept/selector.rs
Fixes #1338
The config now supports a list of integers and a single integer as the `accept` value.
> feat: Expand serde deserialize impl

- Cargo.lock
- benches/Cargo.toml
Follow up to this commit: https://github.com/lycheeverse/lychee/commit/91c8bc3ef5ed5b7650c73e9ca373d119f027f1ae
https://github.com/bheisler/criterion.rs/pull/602 has been merged and is included in 0.5.1 of criterion, so we can now start using the crates.io version again.
> chore: Move back to creates.io version of criterion

- .github/workflows/ci.yml
Based on https://corrode.dev/blog/tips-for-faster-rust-compile-times/
> Try to improve build times

- lychee-bin/src/main.rs
- lychee-bin/tests/cli.rs
Previously, when using JSON as the output format, any supplementary warnings included in the output would invalidate the JSON structure. This pull request addresses this issue by redirecting any extra warnings to `stderr`. This change guarantees that the output remains valid JSON even when additional warnings are present.
Fixes https://github.com/lycheeverse/lychee/issues/1355
> Always output valid JSON with `--format=json`

- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
This PR adds the missing `include_mail` flag to the config file. It also includes a test to ensure that the flag is working correctly.
Fixes https://github.com/lycheeverse/lychee/issues/1354
> Merge missing `include_mail` flag into config

- lychee-bin/tests/cli.rs
I was getting the following error while running the tests for the Arch Linux package:
````
--- STDOUT:              lychee::cli cli::test_failure_github_404_no_token ---
running 1 test
test cli::test_failure_github_404_no_token ... FAILED
failures:
failures:
cli::test_failure_github_404_no_token
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 68 filtered out; finished in 0.27s
--- STDERR:              lychee::cli cli::test_failure_github_404_no_token ---
thread 'cli::test_failure_github_404_no_token' panicked at /usr/src/debug/rust/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5:
Unexpected stdout, failed var.contains(There were issues with Github URLs. You could try setting a Github token and running lychee again.)
├── var: Issues found in 1 input. Find details …
```
> fix(tests): update the expected output in cli tests

- fixtures/TEST_DETAILED_JSON_OUTPUT_ERROR.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/status.rs
Currently if the status response has no status code, json output contains only a text field which gives no real information about the cause of the problem. The patch adds field with more detailed information when the status response contains some details.
> status.rs: Make json output more verbose

- lychee-lib/src/client.rs
- lychee-lib/src/types/error.rs
Closes #1368. Note that this is only a way of solving the issue.
Environment:
OS: Windows x64
Shell: PowerShell 7.4.1
> Set URI to HTTPS for ErrorKind::InsecureURL

- fixtures/fragments/file1.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/extract/markdown.rs
Fixes issue https://github.com/lycheeverse/lychee/issues/1366, where headings with inline code did not have their fragments generated properly.
> Fixed fragment generation for headings with inline code

- Cargo.lock
- Cargo.toml
- README.md
- lychee-bin/Cargo.toml
- lychee-bin/tests/usage.rs
- lychee-lib/Cargo.toml
This way, we have the version number in fewer places. Makes missing version numbers less likely.
> Bump to version; move to workspace versioning

- lychee-bin/tests/cli.rs
I'm getting the following test failure locally while build the latest version for Arch Linux:
```diff
-"error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (certificate has expired)"
+String("error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091: (certificate has expired)")
```
This PR fixes that via performing separate `assert` checks on the output (since the line number in `statem_clnt.c` depends on the platform)
I already built the Arch Linux package with this patch but I'm open to other suggestions. Just wanted to bring this up to your attention! :bear:
> fix(tests): update the asserts in expired SSL certificate test

- README.md
- lychee-lib/src/types/accept/selector.rs
Treat sites with 403 status codes as broken links, reverting back default behavior implemented under #1157 (PR #1167).
> fix: Treat sites with 403 status codes as broken links

- .pre-commit-hooks.yaml
- README.md
Adds support for pre-commit as per discussion #1360   
Relies on the docker image releases, & this referenced image tag shouble be incremented with each package release; i.e. updating the `entry` field in `.pre-commit-hooks.yaml`.
An example `.pre-commit-config.yaml` is provided in the changes to the `README`.
> feat: added support for pre-commit

- Cargo.lock
- lychee-lib/Cargo.toml
- lychee-lib/src/chain/mod.rs
- lychee-lib/src/checker.rs
- lychee-lib/src/client.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/quirks/mod.rs
- lychee-lib/src/types/basic_auth/credentials.rs
As discussed with you @mre this is a first fully functional version of a simple plugin system in lychee. The first approach of using a middleware system turned out to be more complex than necessary and it would not be possible to use Extism in that case, because there would be no way to pass a `next` function to Extism. Instead I came up with `Chain` and `Chainable`. Conceptually having a request chain and a response chain would be very similar to the middleware approach. Instead of a `next` function an element in a chain returns a `ChainResult` which can prematurely return a result in the chain.
The field `request_chain` is added to `ClientBuilder` and `Client`. This chain is `traverse`d before making a request in `check_website`. `check_file` and `check_mail` are not affected. …
> Simple plugin system

- lychee-bin/src/commands/check.rs
- lychee-bin/src/stats.rs
- lychee-lib/src/client.rs
- lychee-lib/src/types/status.rs
With the upgrade to `reqwest` 0.12, we can finally handle a long-standing issue, when Urls could not be parsed to Uris. Previously, we would panic, but we can now handle that situation gracefully and return an error instead.
I've also renamed `Status::is_failure` to `Status::is_error`, because the notion of failures no longer exists in the codebase and we use the term "error" consistently throughout the codebase instead. This is technically a breaking change in the API, but it's fine since we have not released a stable version yet.
More information about the URI parsing issue:
- https://github.com/lycheeverse/lychee/issues/539
- https://github.com/seanmonstar/reqwest/issues/668
> Gracefully handle invalid URIs

- README.md
- lychee-bin/src/options.rs
- lychee-lib/src/chain/mod.rs
- lychee-lib/src/client.rs
- lychee-lib/src/filter/mod.rs
- lychee-lib/src/types/status.rs
These errors puzzled me over in https://github.com/lycheeverse/lychee/pull/1422, and I split out this PR to fix them.
> Fix clippy errors

- README.md
First of all, thank you for this very useful tool!
I ran into an issue while trying to add lychee to the pre-commit hook. Here is the account of the steps that I took.
1. I copied the following pre-commit config code from the [README](https://github.com/lycheeverse/lychee?tab=readme-ov-file#pre-commit-usage) into my project's `.pre-commit-config.yaml`:
```sh
repos:
- repo: https://github.com/lycheeverse/lychee.git
rev: 0.15.1
hooks:
- id: lychee
args: ["--no-progress", "--exclude", "file://"]
```
2. While committing files, pre-commit returned this:
```console
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '0.15.1')
return code: 1
stdout: (none)
stderr:
error: pathspec '0.15.1' did not match any file(s) known to git
Check the log at ... …
```
> Fix typo in pre-commit config in README

- README.md
Thanks for this great library!
https://github.com/sindresorhus/execa/pull/1120
> Add Execa to list of users

- lychee-lib/src/types/uri/valid.rs
Fixes #1436
So actually I think it's never necessary to remove the `mailto:` prefix. @mre tell me if you disagree. I assume that this was done for cosmetic purposes in the CLI output. But I even prefer to keep the scheme in the CLI output since it feels more correct and terminal emulators then detect the address as correct URL so that you can click on it to send a mail to that address using your email application. (noticed in Alacritty)
> Don't trim mailto: prefix when converting a Uri into a string

- README.md
- fixtures/fallback-extensions/index.html
- fixtures/fallback-extensions/other.htm
- lychee-bin/src/client.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/client.rs
In many circumstances (GitHub Pages, Apache configured with MultiViews, etc), web servers process URIs by appending the `.html` file extension when no file is found at the path specified by the URI but a `.html` file corresponding to that path _is_ found.
To allow Lychee to use the fast, offline method of checking such files locally via the `file://` scheme, let's handle this scenario gracefully by adding the `--auto-append-html-fileext` option.
This is especially nice to have when migrating sites that have been run on, say, a web app, to a static site generated by Hugo, [as I am trying to do with Git's home page](https://github.com/git/git-scm.com/pull/1804).
> Add a mode to handle "pretty URLs", i.e. URIs without `.html` extension

- lychee-lib/src/chain/mod.rs
The documentation for `RequestChain` was lacking. It's not immediately clear what this type does for newcomers. It's a significant type to understand lychee, though, so I decided to extend the docs and add an example.
> Extend documentation for `RequestChain`

- README.md
Hi again :wave:
This adds the new `testers.lycheeLinkCheck` to the Installation section, as a follow-up to the conversation with @mre starting at https://github.com/lycheeverse/lychee/issues/1303#issuecomment-2016857155.
I think it's brief enough to fit the Installation section, and with infrastructure as code, putting something in file is the act of installing something, so I think it makes sense to put it here despite not being a shell command.
The text itself is sufficient to get users familiar with Nix started, and the links provide more details.
I can change it up if we need to, but here's the ~first~ second version, [rendered](https://github.com/roberth/lychee/blob/e25ef83/README.md#nixos).
> README: Add Nixpkgs to Installation

- README.md
:tada: since some days `lychee` is also available as a package into openSUSE Tumbleweed's official repositories! I just felt free to also add it to the README :smile:
> Add openSUSE Tumbleweed to the installation instructions

- lychee-lib/src/types/input.rs
Attempts to fix this [issue](https://github.com/lycheeverse/lychee/issues/1459).
This has resulted in some failing tests on Linux. Will revise.
Edit:
Fixed Linux tests. Let me know if you have any suggestions for improvement.
> Fix: Windows drive paths misidentified as URLs

- .github/workflows/debug_build.yml
- .github/workflows/release.yml
- Dockerfile-CI.Dockerfile
- Dockerfile-CI.alpine.Dockerfile
> Harmonizes naming pattern of pre-built binaries and unlocks latest permalink

- .github/workflows/debug_build.yml
- .github/workflows/release.yml
> ci: fix wrong cpu-arch tag on macos release assets

- lychee-lib/src/extract/markdown.rs
WIP for https://github.com/lycheeverse/lychee/issues/1409.
Accidentally closed #1410 by rebasing on top of master, then pushing mid-rebase and don't have permissions to push there. 😅 So reopening here.
@jan-ferdinand fyi
The underlying issue is still not fixed. Just rebased.
@thomas-zahner let me know if you're still looking into this one.
> test: fail when interpreting md footnote as link

- README.md
_It works on my machine!_ ©
```
❯ sudo port install lychee
--->  Computing dependencies for lychee
--->  Fetching archive for lychee
--->  Attempting to fetch lychee-0.14.3_0.darwin_20.x86_64.tbz2 from https://packages.macports.org/lychee
--->  Attempting to fetch lychee-0.14.3_0.darwin_20.x86_64.tbz2.rmd160 from https://packages.macports.org/lychee
--->  Installing lychee @0.14.3_0
--->  Activating lychee @0.14.3_0
--->  Cleaning lychee
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
❯ lychee --help
A fast, async link checker
Finds broken URLs and mail addresses inside Markdown, HTML, `reStructuredText`, websites and more!
```
> chore(docs): mention MacPorts install in README.md

- lychee-bin/src/formatters/stats/markdown.rs
Fixes [`MD041` - First line in a file should be a top-level heading](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md041.md)
> markdown.rs: make first line a top-level heading

- Cargo.lock
- lychee-lib/Cargo.toml
- lychee-lib/src/extract/html/html5ever.rs
- lychee-lib/src/extract/html/html5gum.rs
- lychee-lib/src/extract/markdown.rs
- lychee-lib/src/extract/mod.rs
- lychee-lib/src/extract/plaintext.rs
Preconnect links are used to establish a server connection without loading a specific resource yet.
Not always do these links point to a URL that should return a 200, and they are not user-facing, i.e. they don't show up in the final rendered version of a page.
Therefore, I think we should exclude them at all; not even in `--include-verbatim`
mode, as they might not point to a valid resource.
Fixes #897
> Don't check preconnect links

- README.md
As of almost two weeks ago, Git's home page at https://git-scm.com/ was switched to a static website that uses lychee to verify links (already catching a broken one: https://github.com/gitgitgadget/git/pull/1812).
For substantially longer, the Git Credential Manager uses lychee to validate the links in its documentation.
> README: The Git home page and Git Credential Manager use lychee

- lychee-lib/src/extract/html/html5ever.rs
Resolves #1499
As discussed in #1187
> Exclude `rel=dns-prefetch` links

- .github/workflows/ci.yml
- Cargo.lock
- README.md
- lychee-bin/Cargo.toml
- lychee-bin/src/main.rs
The console subscriber is the source of quite a few papercuts like https://github.com/lycheeverse/lychee/issues/1513.
Since we don't use it at the moment, I decided to remove it.
> fix: Remove tokio console subscriber

- lychee-bin/src/archive/mod.rs
- lychee-bin/src/archive/wayback/mod.rs
- lychee-bin/src/commands/check.rs
> Respect timeout when retrieving archived link

- lychee-lib/src/collector.rs
- lychee-lib/src/extract/html/html5ever.rs
- lychee-lib/src/extract/html/html5gum.rs
This fixes issue #1462 by remove plaintext uri parsing
in html5ever and pruning attribute-less URIs in html5gum
>  Ignore textContent links in html nodes

- README.md
- lychee-bin/src/commands/check.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/accept/mod.rs
- lychee-lib/src/types/accept/range.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/mod.rs
- lychee-lib/src/types/status_code/excluder.rs
- lychee-lib/src/types/status_code/mod.rs
- lychee-lib/src/types/status_code/selector.rs
Closes #1400
This introduces an option `--cache-exclude-status`, which allows specifying a range of HTTP status codes which will be ignored from the cache.
> Allow excluding cache based on status code

- lychee-bin/Cargo.toml
- Since release-plz has been added (#1510), now releases have tags like `{{ package }}-v{{ version }}` ([see `git_tag_name`](https://release-plz.ieni.dev/docs/config#the-git_tag_name-field)).
- The change in #1464 removed the usage of versions (really tag name) in the archive name.
Previous to this patch, `cargo binstall` is using third-party source QuickInstall to install binaries.
```
$ cargo binstall lychee --manifest-path lychee-bin/Cargo.toml --dry-run
INFO resolve: Resolving package: 'lychee'
INFO resolve: Verified signature for package 'lychee-0.16.1-x86_64-unknown-linux-gnu': timestamp:1728250139	file:lychee-0.16.1-x86_64-unknown-linux-gnu.tar.gz	hashed
WARN The package lychee v0.16.1 (x86_64-unknown-linux-gnu) has been downloaded from third-party source QuickInstall
```
After …
> Update `pkg-url` for cargo binstall

- lychee-lib/src/extract/html/html5ever.rs
- lychee-lib/src/extract/html/html5gum.rs
Thanks to great work in PR #1187 , which deals with a similar issue to exclude "preconnect" and is therefore a good preparation for this PR.
Fixes #1209
> Ignore links in prefix attributes

- README.md
Today I encountered some interesting projects using lychee
> Add interesting projects who use lychee

- lychee-lib/src/client.rs
- lychee-lib/src/types/error.rs
This pull request fixes an issue where our error type was too large. The `octocrab` error variant is now boxed using `Box<octocrab::Error>`. This should fix the current clippy issues.
> Box Octocrab error as it is too large

- fixtures/TEST_STYLESHEET_LINK.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/extract/html/html5ever.rs
- lychee-lib/src/extract/html/html5gum.rs
This pull request fixes an issue where email addresses were being detected as links in elements with `ref="stylesheet"`.
The issue occurred when virtual/framework-specific stylesheet paths that start with "/@" or "@" were encountered. These paths are typically resolved by dev servers or build tools and are not real URLs. The fix ensures that these paths are skipped.
Fixes #1538.
> Fix skipping of email addresses in stylesheets

- fixtures/configs/format.toml
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
This pull request fixes the format option in the configuration file. Previously, the format option was not being properly recognized.
Fixes #1533
> Fix format option in configuration file

- lychee-bin/tests/cli.rs
This pull request includes a refactoring of the cache handling test to make it more robust. The cache handling test now ensures a clean state before running.
> Refactor cache handling test to make it more robust

- fixtures/fragments/file.html
- fixtures/fragments/file1.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/extract/markdown.rs
- lychee-lib/src/utils/fragment_checker.rs
Fixes https://github.com/lycheeverse/lychee/issues/1534 and https://github.com/lycheeverse/lychee/issues/1467
> Ignore casing when processing markdown fragments + check for percent encoded ancors

- Cargo.lock
- fixtures/TEST_DETAILED_JSON_OUTPUT_ERROR.md
- fixtures/TEST_INVALID_URLS.html
- lychee-bin/Cargo.toml
- lychee-bin/src/commands/check.rs
- lychee-bin/src/formatters/response/color.rs
- lychee-bin/src/formatters/response/emoji.rs
- lychee-bin/src/formatters/response/mod.rs
- lychee-bin/src/formatters/response/plain.rs
- lychee-bin/src/formatters/stats/compact.rs
- lychee-bin/src/formatters/stats/detailed.rs
- lychee-bin/src/formatters/stats/markdown.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/error.rs
- lychee-lib/src/types/response.rs
- lychee-lib/src/types/status.rs
With the last lychee release, we simplified the status output for links.
While this reduced the visual noise, it also accidentally caused the source of errors to not be printed anymore. This change brings back the additional error information as part of the final report output. Furthermore, it shows the error information in the progress output if verbose mode is activated.
Fixes #1487
Cleaned-up version of #1521.
> Fix: Bring back error output for links

- lychee-lib/src/extract/markdown.rs
By default, `pulldown_cmark` produces multiple text events if it detects an `_`. That is for performance reasons. More information [here](See https://github.com/pulldown-cmark/pulldown-cmark/issues/146).
The correct way to handle this is by using the [`TextMergeStream`](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/utils/struct.TextMergeStream.html) helper-struct, which provides an iterator that merges consecutive `Event::Text` events into one.
With this, we can correctly parse links like `http://example.com/_/foo`.
Fixes #1529
> Support underscores in Markdown URLs

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- Dockerfile-CI.Dockerfile
In our migration to Bookworm, we missed a few places. The outdated images might be a reason why we see more Docker build errors lately. In any case, it's best if we use the latest image everywhere.
> Update all Docker images to Debian Bookworm

- lychee-bin/tests/cli.rs
- lychee-lib/src/quirks/mod.rs
Adds quirks support for the following URL types: 
- `https://www.youtube.com/embed/BIguvia6AvM`
- `https://www.youtube-nocookie.com/embed/BIguvia6AvM`
Just like for the other YouTube URLs, this is done by checking the video thumbnail instead of the actual video link (which can `200`, even if the video got deleted).
Fixes #1562
> Add quirks support for `youtube-nocookie.com` and youtube embed URLs

- lychee-bin/tests/cli.rs
- lychee-lib/src/retry.rs
I'm not seeing any retries.
I'm very new to rust, so probably missing how it's supposed to work, but this change made retries work for me.
> Fix retries

- .github/workflows/docker.yml
As outlined in https://github.com/lycheeverse/lychee/issues/1432#issuecomment-2477830138, the current workflow won't push to the Docker registry when a release is cut because releases now include a pull request.
This pull request increases the number of conditions under which a Docker image can be pushed.
Closes https://github.com/lycheeverse/lychee/issues/1432.
> Allow Docker pushes on release branches

- Cargo.lock
- Cargo.toml
- lychee-bin/CHANGELOG.md
- lychee-bin/Cargo.toml
- lychee-lib/CHANGELOG.md
* `lychee`: 0.17.0 -> 0.18.0
* `lychee-lib`: 0.17.0 -> 0.18.0 (⚠️ API breaking changes)
```
--- failure inherent_method_const_removed: pub method is no longer const ---
Description:
A publicly-visible method or associated fn is no longer `const` and can no longer be used in a `const` context.
ref: https://doc.rust-lang.org/reference/const_eval.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.37.0/src/lints/inherent_method_const_removed.ron
Failed in:
Collector::new in /tmp/.tmptebDB6/lychee/lychee-lib/src/collector.rs:51
Collector::new in /tmp/.tmptebDB6/lychee/lychee-lib/src/collector.rs:51
--- failure method_parameter_count_changed: pub method parameter count changed ---
Description:
A publicly-visible method now takes a different number of parameters.
ref: …
```
> chore: release v0.18.0

- README.md
- docs/TROUBLESHOOTING.md
- lychee-bin/src/formatters/mod.rs
- lychee-bin/src/formatters/response/mod.rs
- lychee-bin/src/formatters/response/task.rs
- lychee-bin/src/options.rs
fixes #1610
- Implemented OutputMode::Task for checkbox formatting
- Updated task.rs formatter to support the new feature
- Fixed Broken Link Using Wayback Machine (https://wilsonmar.github.io/maximum-limits/ -> )
> Add Checkbox Formatting Option for Markdown Reports

- fixtures/fragments/file.html
- fixtures/fragments/file1.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/utils/fragment_checker.rs
The empty "#" and "#top" fragments are always valid without related HTML element. Browser will scroll to the top of the page. Hence lychee must not fail on those.
Fixed #1599
> fix: do not fail on empty # and #top fragments

- Cargo.lock
- Cargo.toml
- lychee-bin/CHANGELOG.md
- lychee-bin/Cargo.toml
- lychee-lib/CHANGELOG.md
* `lychee`: 0.18.1
* `lychee-lib`: 0.18.1
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- do not fail on empty # and #top fragments (#1609)
- Fix Porgressbar rendering Checkbox (Fixes [#1626](https://github.com/lycheeverse/lychee/pull/1626)) ([#1627](https://github.com/lycheeverse/lychee/pull/1627))
- Add Checkbox Formatting Option for Markdown Reports ([#1623](https://github.com/lycheeverse/lychee/pull/1623))
- Fix new clippy lints ([#1625](https://github.com/lycheeverse/lychee/pull/1625))
- Bump the dependencies group with 3 updates ([#1604](https://github.com/lycheeverse/lychee/pull/1604))
- Bump the dependencies group with 3 updates ([#1602](https://github.com/lycheeverse/lychee/pull/1602))
- Bump the dependencies group with 6 updates …
> chore: release v0.18.1

- Cargo.lock
- lychee-bin/Cargo.toml
- lychee-bin/src/formatters/stats/compact.rs
- lychee-bin/src/formatters/stats/detailed.rs
- lychee-bin/src/formatters/stats/markdown.rs
- lychee-bin/src/formatters/stats/mod.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/input.rs
Implements the feature requested in #1619 
The helper function is named `sort_stat_map` as it's used for both errors and suggestions in the markdown module, and it could be used for other `ResponseStats` maps as well.
`sort_stat_map` returns a `Vec` of key-value pairs, it's only used for iterating through each pair so using a map isn't currently necessary.
The JSON and raw formatters are unchanged since they don't loop through the `ResponseStats` maps. 
This is my first pull request, so any feedback/suggestions are more than welcome and appreciated :alien:
> Sort compact/detailed/markdown error output by file path

- README.md
- fixtures/configs/smoketest.toml
- lychee-bin/src/client.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee.example.toml
Changed the configuration parameter `base` to `base_url` to improve clarity (fixes #1607)
> renamed `base` to `base_url` (fixes #1607)

- .github/workflows/release-binary.yml
I tried to install Lychee with [Ubi](https://github.com/houseabsolute/ubi) through [Mise](https://mise.jdx.dev), and it fails in macOS because `ubi expects the binaries to be in a compressed file, and that's not the case for the macOS binaries.
This PR fixes that by also including the a `.tar.gz` version for the macOS binary.
> Release the macOS binaries also as `.tar.gz`

- fixtures/LINK_PERIOD.html
- lychee-bin/tests/cli.rs
Related: https://github.com/lycheeverse/lychee/issues/1640
> Add tests for URL extraction ending with a period

- lychee-bin/src/formatters/stats/markdown.rs
Changes formatting of URLs in markdown output so it works well with GitHub Actions output (#1636, https://github.com/lycheeverse/lychee-action/issues/271)
> format markdown URLs with <> instead of []() (#1636)

- README.md
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/file.rs
- lychee-lib/src/types/input.rs
- lychee-lib/src/types/mod.rs
This adds support for overwriting extensions:
```
lychee . --extensions md,html,txt,json,yaml
```
The above would only check these extensions.
This was enabled by moving to `ignore` (#1500 by @thomas-zahner).
I'm not 100% convinced about the design yet. Feedback welcome!
Guess we should use whatever [`ignore::types::Types`](https://docs.rs/ignore/0.4.23/ignore/types/struct.Types.html) for file extension matching as it's well-maintained and more exhaustive. Switching this would remove some custom code we have in `FileType`.
Fixes #410
> Add support for custom file extensions in link checking.

- README.md
- lychee-bin/src/options.rs
- lychee-lib/src/types/accept/range.rs
Fixes #1667 .
Along the way I also reworded the docs in a manner that felt easier to read for me, and made sure we have tests for off-by-one scenarios because these errors are so easy to make :) I updated the README's help output as well.
> Fix accept/exclude range syntax and docs

- README.md
This PR updates the URL from https://hello-rust.show/10/ to https://hello-rust.github.io/10/ 
The `hello-rust.show` domain is no longer valid.
> Fix: outdated link

- README.md
- lychee-bin/src/client.rs
- lychee-bin/src/options.rs
- lychee-lib/src/client.rs
Feature suggested in: https://github.com/lycheeverse/lychee/issues/1232
> Add TLS version option

- README.md
- lychee-bin/src/options.rs
This makes the output a bit nicer by providing a list of possible values:
```sh
❯❯❯ lychee --min-tls=TLSv1_4 
error: invalid value 'TLSv1_4' for '--min-tls <MIN_TLS>'
[possible values: TLSv1_0, TLSv1_1, TLSv1_2, TLSv1_3]
tip: a similar value exists: 'TLSv1_3'
For more information, try '--help'.
```
Follow up of https://github.com/lycheeverse/lychee/pull/1655
> Add possible values for minimum TLS version in help message

- lychee-lib/src/extract/markdown.rs
partially closes #1650 
Obsidian style links that point to a file without extension are not supported
> detect wikilinks, prevent plaintext extraction from links 

- Makefile
- README.md
- docs/TROUBLESHOOTING.md
- lychee-bin/src/client.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
Updated the documentation in https://github.com/lycheeverse/lycheeverse.github.io/pull/93 accordingly.
> Remove exclude mail

- lychee-lib/src/extract/markdown.rs
> fix: ignore gitlab table of content in wikilinks

- fixtures/fragments/file1.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/checker/file.rs
- lychee-lib/src/client.rs
- lychee-lib/src/utils/fragment_checker.rs
- related to https://github.com/lycheeverse/lychee/issues/1709
What's in this PR:
- only check fragments for files
- better err type
- more info in err msg
BTW, I'm not sure if the `Client.check_fragment` is used by any caller. cc @mre
> fix: only check the fragment when it's a file

- fixtures/configs/lychee.toml
- lychee-bin/src/main.rs
- lychee-bin/tests/cli.rs
- fix https://github.com/lycheeverse/lychee/issues/1704
> feat: raise error when the default config file is invalid

- Cargo.lock
- Cargo.toml
- lychee-bin/CHANGELOG.md
- lychee-bin/Cargo.toml
- lychee-lib/CHANGELOG.md
* `lychee-lib`: 0.18.1 -> 0.19.0 (⚠ API breaking changes)
* `lychee`: 0.18.1 -> 0.19.0
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field Input.headers in /tmp/.tmpuG4vCC/lychee/lychee-lib/src/types/input.rs:114
--- failure derive_trait_impl_removed: built-in derived trait no longer implemented ---
Description:
A public type has stopped deriving one or more traits. This can break downstream code …
```
> chore: release v0.19.0

- lychee-lib/src/checker/file.rs
As discussed in:
- https://github.com/lycheeverse/lychee/issues/1709
Otherwise, this may cause "Too many open files" because the `self.check_fragment` needs to open the file to build the `FragmentInput`.
> fix: skip the fragment check if the uri doesn't contain fragment

- Cargo.lock
- Cargo.toml
- lychee-bin/CHANGELOG.md
- lychee-bin/Cargo.toml
- lychee-lib/CHANGELOG.md
* `lychee-lib`: 0.19.0 -> 0.19.1 (✓ API compatible changes)
* `lychee`: 0.19.0 -> 0.19.1
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- skip the fragment check if the uri doesn't contain fragment ([#1730](https://github.com/lycheeverse/lychee/pull/1730))
- Update changelog
</blockquote>
<blockquote>
- Don't echo potentially sensitive header data ([#1728](https://github.com/lycheeverse/lychee/pull/1728))
- Update changelog
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.19.1

- lychee.example.toml
fix https://github.com/lycheeverse/lychee/issues/1699
Identical to https://github.com/lycheeverse/lychee/pull/1702 but rebased with master
> docs: improve lychee.example.toml (lycheeverse#1699)

- examples/archive/archive.rs
- examples/chain/chain.rs
- flake.lock
- lychee-bin/tests/cli.rs
- lychee-lib/src/archive/wayback/mod.rs
- lychee-lib/src/extract/html/html5gum.rs
- lychee-lib/src/extract/markdown.rs
Pipeline fails because of Rust 1.88 was released yesterday with new clippy suggestions.
The most interesting part of this PR is that I removed `#[ignore]` from two tests as I noticed that they are actually passing. I assume it's because the issues were addressed in the meantime. Or is there a reason we should still ignore them?
> Clippy 1.88

- fixtures/fragments/file.html
- lychee-bin/tests/cli.rs
- lychee-lib/src/utils/fragment_checker.rs
What can be handled:
- GitHub default README + Gist fragment (by adding the `user-content-` prefix)
- GitHub PR discussion (by nature)
- Gist files (by nature)
What cannot be handled:
- GitHub markdown files on any specific path
- includes `blob/master/README.md`
- issue comments
- like `https://github.com/PyO3/pyo3/issues/1800#issuecomment-906786649`
We have to simulate with a headless browser library to support these cases.
> feat: add 'user-content-' prefix to support github markdown fragment

- Cargo.lock
- lychee-bin/Cargo.toml
- lychee-bin/src/formatters/stats/compact.rs
- lychee-bin/src/formatters/stats/detailed.rs
- lychee-bin/src/formatters/stats/mod.rs
Fixes #1758
Replaces the unmaintained `human-sort` crate with `numeric-sort` to fix panic issues in recent Rust versions.
- `human-sort` is unmaintained
- Causes "user-provided comparison function does not correctly implement a total order" panic in recent Rust versions
- Replace `human-sort` (0.2.2) with `numeric-sort` (0.1.5)
- Update all usages of `human_sort::compare` to `numeric_sort::cmp`
- The new crate provides the same natural/human sorting behavior
- Updated `Cargo.toml` dependency
- Modified sorting logic in:
- `lychee-bin/src/formatters/stats/mod.rs`
- `lychee-bin/src/formatters/stats/compact.rs`
- `lychee-bin/src/formatters/stats/detailed.rs`
> Replace unmaintained human-sort with numeric-sort

- fixtures/fragments/file1.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/checker/website.rs
Fixes: #1737
The remote URL/website checker currently passes all URLs with fragments to the fragment checker as HTML document, even if it is a different or unsupported MIME type. This can cause false fragment checking for Markdown documents, failures for other MIME types, especially binaries, and unnecessary traffic for large downloads, which are always finished completely, if the fragment checker is invoked.
This commit checks the Content-Type header of the response:
- Only if it is `text/html`, it is passed to the fragment checker as HTML type.
- Only if it is `text/markdown`, of `text/plain` and URL path ends on `.md`, it is passed to the fragment checker as Markdown type.
- In all other cases, the fragment checker is skipped and the HTTP status is returned.
To invoke the fragment …
> feat: skip fragment checking for unsupported MIME types

- lychee.example.toml
This is very common for documentation tools like vitepress, astro, etc.
> docs: add `fallback_extensions` to example config file

- .github/workflows/release-binary.yml
- Dockerfile-CI.alpine.Dockerfile
Add support for 64-bit ARM binary and use in Alpine Linux-based Docker images.
Fixes: https://github.com/lycheeverse/lychee/issues/1745.
> Add support for 64-bit ARM binary

- fixtures/TEST_LOCAL_DIRECTORIES.md
- lychee-bin/tests/cli.rs
- lychee-lib/src/checker/file.rs
81f2605 introduced a new bug. The bug is now described in `test_local_directories`. I've reverted the few lines in file.rs that introduced the bug.
So previously we had:
`[ERROR] file:///home/thomas/Projects/lychee/fixtures/fragments/empty_dir | Cannot find file`
now we're back at:
`[200] file:///home/thomas/Projects/lychee/fixtures/fragments/empty_dir`
This bug was introduced in https://github.com/lycheeverse/lychee/pull/1756. The tests form this PR make sense and can be left unchanged apart from this one difference mentioned above. (which results in the 30/31 OK and 12/11 Errors difference)
@ocavue @mre @katrinafyi Can you explain the reasoning behind removing the `else if`? If there really is a reason behind skipping that check we could introduce a new feature flag for that but I don't …
> Fix local directory checking

- lychee-lib/src/types/error.rs
the comment doesn't make sense and it is identical to InvalidFilePath which is right above it, so I reason this was a copy/paste mistake.
> fix comment for `ErrorKind::InvalidFragment`

- .github/workflows/snap.yml
- README.md
Quick follow-up to #1786 since I saw the workflow isn't passing yet.
> Fix missing identifier in snap build action; add snap install to readme

- snap/snapcraft.yaml
Allows the packaged app to access files and the network.
> snap: enable proper permissions

- lychee-bin/src/commands/dump.rs
- lychee-bin/src/commands/dump_inputs.rs
- lychee-bin/src/commands/mod.rs
- lychee-bin/src/main.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/collector.rs
- lychee-lib/src/types/file.rs
- lychee-lib/src/types/input.rs
Refactor the `dump-inputs` functionality to print all files checked for links and implement file path retrieval with extension filtering in the `Input` module.
I added this because it was hard to troubleshoot the extension changes, but I figured it would also be helpful to people who want to see which files would be checked when they write `lychee .`.
As an added benefit, `dump-inputs` now behaves more like the `check` command and properly ignores hidden files etc.
This is a follow-up to #1559.
Closes #1767.
> Refactor input dumping and path retrieval with extension filtering

- fixtures/example_dir/example.html
- fixtures/example_dir/example.md
- fixtures/example_dir/example.ts
- fixtures/example_dir/example.tsx
- fixtures/glob_dir/example.html
- fixtures/glob_dir/example.md
- fixtures/glob_dir/example.ts
- fixtures/glob_dir/example.tsx
- lychee-bin/src/commands/dump_inputs.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/types/input.rs
Ensure that files specified via glob patterns are always checked, regardless of their extensions. This change addresses the issue where no links were found due to configuration errors. Additional tests have been added to verify glob pattern handling and extension checks.
Fixes lycheeverse/lychee-action#305
> Always check files explicitly if specified by user or matched by user glob

- Dockerfile-CI.Dockerfile
- Dockerfile-CI.alpine.Dockerfile
Don't use link to latest stable release for nightly.
> Don't use link to latest stable release for nightly

- lychee-lib/src/collector.rs
- lychee-lib/src/types/input.rs
I realized we don't need to create the extractor every time in a loop. Also cleaning up the input handling a bit.
This should not change any functionality.
> Refactor collector and input

- lychee-bin/tests/cli.rs
Related to https://github.com/lycheeverse/lychee/issues/1819
> Add test for making sure URL inputs always get checked

- README.md
- lychee-bin/src/options.rs
this more clearly documents the behaviour of these flags. this makes no changes to behavior. as always, this documents the usage as i observe right now and does not presume that this behaviour is good or correct.
i also hope to clarify some more subtle points:
- the base-url is uniformly applied to every local file being checked, regardless of the filesystem path of each local file. this means that a relative link `a/b` resolves to exactly the same URL no matter which local file it appears in.
- base-url is affected by trailing slashes.
- define behavior when root-dir and base-url are both specified. namely, root-dir becomes a subpath of the base-url's domain.
honestly, the more i think about it, the more i think this behavior is wrong or has diverged from its original intention. for …
> clarify `--base-url` and `--root-dir` and their interactions

- README.md
- lychee-bin/src/files_from.rs
- lychee-bin/src/main.rs
- lychee-bin/src/options.rs
- lychee-bin/tests/cli.rs
- lychee-bin/tests/usage.rs
This allows providing a list of inputs from a file or `stdin`.
1. Create a `inputs.txt` file with all the inputs (files) you'd like to check for broken links.
2. Pass that to `lychee` with
```sh
lychee --files-from inputs.txt
```
lychee will then use the files from `inputs.txt` as inputs. You can still provide custom inputs as well with
```sh
lychee --files-from inputs.txt another_input.md
```
The inputs file can contain comments, such as
```text
some_input.txt
```
Closes: https://github.com/lycheeverse/lychee/issues/662
> Implement `--files-from` Option

- lychee-bin/src/commands/check.rs
- lychee-bin/src/formatters/stats/compact.rs
- lychee-bin/src/formatters/stats/markdown.rs
- lychee-bin/src/formatters/stats/mod.rs
- lychee-bin/src/stats.rs
- lychee-lib/src/extract/mod.rs
- lychee-lib/src/lib.rs
- lychee-lib/src/types/base.rs
- lychee-lib/src/types/input/content.rs
- lychee-lib/src/types/input/input.rs
- lychee-lib/src/types/input/mod.rs
- lychee-lib/src/types/input/resolver.rs
- lychee-lib/src/types/input/source.rs
- lychee-lib/src/types/mod.rs
- lychee-lib/src/types/request.rs
- lychee-lib/src/types/resolver.rs
- lychee-lib/src/types/response.rs
- lychee-lib/src/utils/request.rs
for parts of the link checking pipeline including and downstream of `InputContent`, this PR replaces `InputSource` fields with `ResolvedInputSource`. specifically, this means the structs `InputContent`, `Request`, and `Response`. 
this makes sense for two reasons:
- conceptually, once you are able to read the content of a source, you must have resolved globs to a real path, so using ResolvedInputSource is more accurate.
- in practice, InputContent's source field was never set to a FsGlob variant, it always used variant cases which are shared with ResolvedInputSource. this is because InputContent was constructed by [pattern matching out of a ResolvedInputSource](https://github.com/lycheeverse/lychee/blob/be26d02c80825bb485ec504f39787a0df6310a34/lychee-lib/src/types/input/input.rs#L208-L221) …
> refactor!: use `ResolvedInputSource` downstream of `InputContent`

- .github/workflows/ci.yml
CI is currently failing with this error:
`'cargo-fmt' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'.`
adding rustfmt as a toolchain component fixes is
> Fix CI lint by adding rustfmt in the the toolchain components

- lychee-bin/src/client.rs
- lychee-bin/tests/cli.rs
- lychee-lib/src/checker/file.rs
- lychee-lib/src/types/error.rs
this makes it clearer which files are causing the link check to fail. it also lets us customise the message in the special case of `--index-files ''`, which could otherwise be confusing with a generic message.
the messages are:
```
[ERROR] file:///h | Cannot find index file within directory: An index file (index.html) is required
[ERROR] file:///h | Cannot find index file within directory: An index file (index.html, or index.htm) is required
[ERROR] file:///h | Cannot find index file within directory: An index file (index.html, index.htm, or index.md) is required
```
and for the `--index-files ''` case:
```
[ERROR] file:///h | Cannot find index file within directory: No directory links are allowed because index_files is defined and empty
```
i do wonder if this last error message is still …
> feat: improve InvalidIndexFile error to mention index file names
